// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.4
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module IDCT_thread (
        ap_clk,
        ap_rst,
        ReadEnablePort_0,
        ReadEnablePort_0_ap_vld,
        ReadEmptyPort_0,
        ReadDataPort_0,
        WriteEnablePort_0,
        WriteEnablePort_0_ap_vld,
        WriteFullPort_0,
        WriteDataPort_0,
        WriteDataPort_0_ap_vld,
        ReadEnablePort_1,
        ReadEnablePort_1_ap_vld,
        ReadEmptyPort_1,
        ReadDataPort_1
);

input   ap_clk;
input   ap_rst;
output  [0:0] ReadEnablePort_0;
output   ReadEnablePort_0_ap_vld;
input  [0:0] ReadEmptyPort_0;
input  [31:0] ReadDataPort_0;
output  [0:0] WriteEnablePort_0;
output   WriteEnablePort_0_ap_vld;
input  [0:0] WriteFullPort_0;
output  [31:0] WriteDataPort_0;
output   WriteDataPort_0_ap_vld;
output  [0:0] ReadEnablePort_1;
output   ReadEnablePort_1_ap_vld;
input  [0:0] ReadEmptyPort_1;
input  [31:0] ReadDataPort_1;

reg[0:0] ReadEnablePort_0;
reg ReadEnablePort_0_ap_vld;
reg[0:0] WriteEnablePort_0;
reg WriteEnablePort_0_ap_vld;
reg[31:0] WriteDataPort_0;
reg WriteDataPort_0_ap_vld;
reg[0:0] ReadEnablePort_1;
reg ReadEnablePort_1_ap_vld;
wire   [31:0] Y_q0;
reg   [31:0] reg_628;
reg   [5:0] ap_CS_fsm = 6'b000000;
wire   [31:0] Y_q1;
reg   [31:0] reg_632;
wire   [31:0] Yc_q0;
reg   [31:0] reg_636;
wire   [31:0] Yc_q1;
reg   [31:0] reg_640;
wire   [2:0] Yc_addr_9_gep_fu_295_p3;
reg   [2:0] Yc_addr_9_reg_1872;
wire   [2:0] Yc_addr_gep_fu_302_p3;
reg   [2:0] Yc_addr_reg_1878;
wire   [2:0] Yc_addr_1_gep_fu_309_p3;
reg   [2:0] Yc_addr_1_reg_1884;
wire   [2:0] Yc_addr_2_gep_fu_316_p3;
reg   [2:0] Yc_addr_2_reg_1889;
wire   [2:0] Yc_addr_3_gep_fu_323_p3;
reg   [2:0] Yc_addr_3_reg_1894;
wire   [2:0] Yc_addr_4_gep_fu_330_p3;
reg   [2:0] Yc_addr_4_reg_1900;
wire   [2:0] Yc_addr_5_gep_fu_337_p3;
reg   [2:0] Yc_addr_5_reg_1906;
wire   [2:0] Yc_addr_6_gep_fu_344_p3;
reg   [2:0] Yc_addr_6_reg_1912;
wire   [0:0] indvar_next1_fu_673_p2;
reg   [0:0] indvar_next1_reg_1918;
wire   [0:0] tmp_4_fu_679_p2;
reg   [0:0] tmp_4_reg_1923;
wire   [0:0] indvar1_phi_fu_518_p4;
wire   [0:0] indvar_next_fu_690_p2;
reg   [0:0] indvar_next_reg_1930;
wire   [31:0] tmp1_fu_705_p2;
reg   [31:0] tmp1_reg_1938;
wire   [0:0] tmp_8_fu_696_p2;
wire   [0:0] indvar_phi_fu_529_p4;
wire   [31:0] block_1_fu_721_p2;
reg   [31:0] block_1_reg_1949;
wire   [31:0] ptData3_0_sum238241_i_cast_fu_754_p1;
reg   [31:0] ptData3_0_sum238241_i_cast_reg_1954;
reg   [5:0] in_addr_1_reg_1959;
wire   [5:0] i_1_fu_764_p2;
reg   [5:0] i_1_reg_1967;
wire   [5:0] row_cast_fu_786_p1;
reg   [5:0] row_cast_reg_1975;
wire   [3:0] row_3_fu_796_p2;
reg   [3:0] row_3_reg_1989;
wire   [5:0] tmp_2_fu_802_p2;
reg   [5:0] tmp_2_reg_1994;
wire   [0:0] exitcond2_fu_790_p2;
wire   [31:0] tmp_2_cast_fu_808_p1;
reg   [31:0] tmp_2_cast_reg_1999;
wire   [3:0] column_2_fu_822_p2;
reg   [3:0] column_2_reg_2007;
wire   [31:0] tmp_49_cast_fu_833_p1;
reg   [31:0] tmp_49_cast_reg_2012;
wire   [0:0] exitcond5_fu_816_p2;
reg   [5:0] Y_addr_9_reg_2022;
reg   [5:0] Y_addr_5_reg_2028;
reg   [5:0] Y_addr_6_reg_2034;
reg   [5:0] Y_addr_1_reg_2040;
reg   [5:0] Y_addr_2_reg_2045;
wire   [2:0] tmp_73_fu_945_p1;
reg   [2:0] tmp_73_reg_2050;
reg   [31:0] Y_load_7_reg_2055;
reg   [31:0] Y_load_8_reg_2061;
reg   [5:0] Y_addr_3_reg_2067;
reg   [5:0] Y_addr_4_reg_2073;
reg   [17:0] tmp_81_reg_2079;
reg   [17:0] tmp_83_reg_2084;
wire   [31:0] y_assign_2_fu_1034_p2;
reg   [31:0] y_assign_2_reg_2089;
wire   [31:0] x_assign_1_fu_1040_p2;
reg   [31:0] x_assign_1_reg_2095;
wire   [31:0] x_assign_2_fu_1046_p2;
reg   [31:0] x_assign_2_reg_2101;
wire   [31:0] y_assign_1_fu_1052_p2;
reg   [31:0] y_assign_1_reg_2107;
wire   [31:0] grp_fu_988_p2;
reg   [31:0] tmp_9_reg_2113;
wire   [31:0] grp_fu_993_p2;
reg   [31:0] tmp_s_reg_2118;
wire   [31:0] grp_fu_998_p2;
reg   [31:0] tmp_10_reg_2123;
wire   [31:0] grp_fu_1003_p2;
reg   [31:0] tmp_11_reg_2128;
reg   [5:0] Y_addr_reg_2133;
reg   [17:0] tmp_76_reg_2139;
reg   [17:0] tmp_77_reg_2144;
wire   [31:0] grp_fu_1058_p2;
reg   [31:0] tmp_25_reg_2149;
wire   [31:0] grp_fu_1063_p2;
reg   [31:0] tmp_26_reg_2154;
wire   [31:0] grp_fu_1068_p2;
reg   [31:0] tmp_29_reg_2159;
wire   [31:0] grp_fu_1073_p2;
reg   [31:0] tmp_30_reg_2164;
wire   [31:0] grp_fu_1078_p2;
reg   [31:0] tmp_33_reg_2169;
wire   [31:0] grp_fu_1083_p2;
reg   [31:0] tmp_34_reg_2174;
wire   [31:0] grp_fu_1088_p2;
reg   [31:0] tmp_37_reg_2179;
wire   [31:0] grp_fu_1093_p2;
reg   [31:0] tmp_38_reg_2184;
wire   [31:0] grp_fu_644_p2;
reg   [31:0] z1_1_reg_2189;
wire   [31:0] z3_3_fu_1145_p2;
reg   [31:0] z3_3_reg_2195;
wire   [31:0] z3_0_fu_1151_p2;
reg   [31:0] z3_0_reg_2201;
reg   [17:0] tmp_84_reg_2207;
reg   [17:0] tmp_85_reg_2212;
reg   [17:0] tmp_86_reg_2217;
reg   [17:0] tmp_88_reg_2222;
wire   [31:0] z3_2_fu_1216_p2;
reg   [31:0] z3_2_reg_2227;
wire   [31:0] z3_1_fu_1221_p2;
reg   [31:0] z3_1_reg_2233;
wire   [5:0] column_cast_fu_1286_p1;
reg   [5:0] column_cast_reg_2239;
wire   [3:0] column_3_fu_1296_p2;
reg   [3:0] column_3_reg_2248;
wire   [31:0] row_1_cast_fu_1306_p1;
reg   [31:0] row_1_cast_reg_2253;
wire   [3:0] row_4_fu_1316_p2;
reg   [3:0] row_4_reg_2261;
wire   [0:0] exitcond4_fu_1310_p2;
reg   [31:0] Yc_load_2_reg_2271;
reg   [31:0] Yc_load_8_reg_2277;
reg   [17:0] tmp_22_reg_2283;
reg   [17:0] tmp_24_reg_2288;
wire   [31:0] y_assign_5_fu_1396_p2;
reg   [31:0] y_assign_5_reg_2293;
wire   [31:0] x_assign_4_fu_1402_p2;
reg   [31:0] x_assign_4_reg_2299;
wire   [31:0] x_assign_5_fu_1408_p2;
reg   [31:0] x_assign_5_reg_2305;
wire   [31:0] y_assign_4_fu_1414_p2;
reg   [31:0] y_assign_4_reg_2311;
wire   [31:0] grp_fu_1350_p2;
reg   [31:0] tmp_6_reg_2317;
wire   [31:0] grp_fu_1355_p2;
reg   [31:0] tmp_7_reg_2322;
wire   [31:0] grp_fu_1360_p2;
reg   [31:0] tmp_15_reg_2327;
wire   [31:0] grp_fu_1365_p2;
reg   [31:0] tmp_16_reg_2332;
reg   [17:0] tmp_14_reg_2337;
reg   [17:0] tmp_20_reg_2342;
wire   [31:0] grp_fu_1420_p2;
reg   [31:0] tmp_28_reg_2347;
wire   [31:0] grp_fu_1425_p2;
reg   [31:0] tmp_32_reg_2352;
wire   [31:0] grp_fu_1430_p2;
reg   [31:0] tmp_50_reg_2357;
wire   [31:0] grp_fu_1435_p2;
reg   [31:0] tmp_52_reg_2362;
wire   [31:0] grp_fu_1440_p2;
reg   [31:0] tmp_55_reg_2367;
wire   [31:0] grp_fu_1445_p2;
reg   [31:0] tmp_56_reg_2372;
wire   [31:0] grp_fu_1450_p2;
reg   [31:0] tmp_59_reg_2377;
wire   [31:0] grp_fu_1455_p2;
reg   [31:0] tmp_60_reg_2382;
wire   [31:0] grp_fu_656_p2;
reg   [31:0] z1_1_1_reg_2387;
wire   [31:0] z3_3_1_fu_1491_p2;
reg   [31:0] z3_3_1_reg_2393;
wire   [31:0] z3_0_1_fu_1497_p2;
reg   [31:0] z3_0_1_reg_2399;
reg   [17:0] tmp_40_reg_2405;
reg   [17:0] tmp_54_reg_2410;
reg   [17:0] tmp_58_reg_2415;
reg   [17:0] tmp_62_reg_2420;
wire   [31:0] z3_2_1_fu_1562_p2;
reg   [31:0] z3_2_1_reg_2425;
wire   [31:0] z3_1_1_fu_1567_p2;
reg   [31:0] z3_1_1_reg_2431;
wire   [3:0] row_5_fu_1647_p2;
reg   [3:0] row_5_reg_2440;
wire   [0:0] exitcond7_fu_1641_p2;
wire   [5:0] tmp_96_fu_1659_p2;
reg   [5:0] tmp_96_reg_2450;
reg   [25:0] tmp_91_reg_2455;
wire   [0:0] tmp_92_fu_1711_p2;
reg   [0:0] tmp_92_reg_2460;
wire   [7:0] phitmp_fu_1737_p3;
reg   [7:0] phitmp_reg_2465;
reg   [5:0] Idct_addr_1_reg_2470;
reg   [5:0] Idct_addr_2_reg_2475;
reg   [5:0] Idct_addr_3_reg_2480;
reg   [5:0] Idct_addr_4_reg_2485;
wire   [4:0] i_3_fu_1828_p2;
reg   [4:0] i_3_reg_2493;
wire   [7:0] Idct_q0;
reg   [7:0] Idct_load_reg_2501;
wire   [7:0] Idct_q1;
reg   [7:0] Idct_load_1_reg_2506;
reg   [5:0] Y_address0;
reg    Y_ce0;
reg    Y_we0;
reg   [31:0] Y_d0;
reg   [5:0] Y_address1;
reg    Y_ce1;
reg    Y_we1;
reg   [31:0] Y_d1;
reg   [5:0] in_address0;
reg    in_ce0;
reg    in_we0;
wire   [15:0] in_d0;
wire   [15:0] in_q0;
wire   [5:0] in_address1;
reg    in_ce1;
reg    in_we1;
wire   [15:0] in_d1;
reg   [5:0] Idct_address0;
reg    Idct_ce0;
reg    Idct_we0;
wire   [7:0] Idct_d0;
reg   [5:0] Idct_address1;
reg    Idct_ce1;
reg   [2:0] Yc_address0;
reg    Yc_ce0;
reg    Yc_we0;
reg   [31:0] Yc_d0;
reg   [2:0] Yc_address1;
reg    Yc_ce1;
reg    Yc_we1;
reg   [31:0] Yc_d1;
reg   [0:0] indvar1_reg_514;
reg   [0:0] indvar_reg_525;
reg   [31:0] block_reg_536;
wire   [0:0] exitcond6_fu_1822_p2;
reg   [5:0] i_reg_547;
wire   [0:0] exitcond_fu_716_p2;
reg   [3:0] row_reg_558;
wire   [0:0] exitcond1_fu_758_p2;
reg   [3:0] column_1_reg_569;
reg   [3:0] column_reg_580;
reg   [3:0] row_1_reg_591;
wire   [0:0] exitcond3_fu_1290_p2;
reg   [3:0] row_2_reg_602;
reg   [4:0] i_2_reg_613;
wire   [31:0] ptData3_0_rec_i_cast_fu_737_p1;
wire   [0:0] grp_wireread_fu_275_p2;
wire   [31:0] p_sum5_cast_fu_853_p1;
wire   [31:0] p_sum6_cast_fu_873_p1;
wire   [31:0] p_sum1_cast_fu_908_p1;
wire   [31:0] p_sum2_cast_fu_928_p1;
wire   [31:0] p_sum3_cast_fu_963_p1;
wire   [31:0] p_sum4_cast_fu_983_p1;
wire   [31:0] p_sum_cast_fu_1109_p1;
wire   [31:0] tmp_97_cast_fu_1333_p1;
wire   [31:0] row_2_cast1_fu_1632_p1;
wire   [31:0] tmp_107_cast_fu_1752_p1;
wire   [31:0] tmp332338_i_cast_fu_1783_p1;
wire   [31:0] tmp333339_i_cast_fu_1800_p1;
wire   [31:0] tmp335340_i_cast_fu_1817_p1;
wire   [31:0] tmp_i_cast_fu_1766_p1;
reg   [31:0] NBLOCKS_fu_206;
wire   [0:0] grp_wireread_fu_262_p2;
reg   [31:0] uiCommand_fu_210;
wire   [31:0] p_Result_2_fu_1846_p5;
wire   [0:0] grp_wireread_fu_288_p2;
wire   [31:0] tmp_51_cast_fu_888_p1;
wire   [31:0] tmp_41_fu_1229_p2;
wire   [31:0] tmp_43_fu_1244_p2;
wire   [31:0] tmp_45_fu_1259_p2;
wire   [31:0] tmp_47_fu_1274_p2;
wire   [31:0] tmp_42_fu_1235_p2;
wire   [31:0] tmp_44_fu_1250_p2;
wire   [31:0] tmp_46_fu_1265_p2;
wire   [31:0] tmp_48_fu_1280_p2;
wire   [31:0] tmp_63_fu_1575_p2;
wire   [31:0] tmp_65_fu_1590_p2;
wire   [31:0] tmp_67_fu_1605_p2;
wire   [31:0] tmp_69_fu_1620_p2;
wire   [31:0] tmp_64_fu_1581_p2;
wire   [31:0] tmp_66_fu_1596_p2;
wire   [31:0] tmp_68_fu_1611_p2;
wire   [31:0] tmp_70_fu_1626_p2;
wire   [31:0] grp_fu_644_p0;
wire   [31:0] grp_fu_644_p1;
wire   [31:0] grp_fu_650_p0;
wire   [31:0] grp_fu_650_p1;
wire   [31:0] grp_fu_656_p0;
wire   [31:0] grp_fu_656_p1;
wire   [31:0] grp_fu_662_p0;
wire   [31:0] grp_fu_662_p1;
wire   [6:0] i_4_cast_fu_727_p1;
wire   [6:0] ptData3_0_rec_i_fu_731_p2;
wire   [6:0] ptData3_0_sum238241_i_fu_742_p5;
wire   [5:0] column_1_cast_fu_812_p1;
wire   [5:0] tmp_49_fu_828_p2;
wire   [2:0] tmp_80_fu_838_p1;
wire   [5:0] p_sum5_fu_841_p5;
wire   [2:0] tmp_82_fu_858_p1;
wire   [5:0] p_sum6_fu_861_p5;
wire   [18:0] tmp_50_cast_fu_878_p1;
wire   [18:0] tmp_51_fu_882_p2;
wire   [2:0] tmp_74_fu_893_p1;
wire   [5:0] p_sum1_fu_896_p5;
wire   [2:0] tmp_75_fu_913_p1;
wire   [5:0] p_sum2_fu_916_p5;
wire   [31:0] grp_fu_933_p0;
wire   [14:0] grp_fu_933_p1;
wire   [31:0] grp_fu_939_p0;
wire   [14:0] grp_fu_939_p1;
wire   [2:0] tmp_78_fu_948_p1;
wire   [5:0] p_sum3_fu_951_p5;
wire   [2:0] tmp_79_fu_968_p1;
wire   [5:0] p_sum4_fu_971_p5;
wire   [31:0] grp_fu_988_p0;
wire   [13:0] grp_fu_988_p1;
wire   [31:0] grp_fu_993_p0;
wire   [14:0] grp_fu_993_p1;
wire   [31:0] grp_fu_998_p0;
wire   [14:0] grp_fu_998_p1;
wire   [31:0] grp_fu_1003_p0;
wire   [13:0] grp_fu_1003_p1;
wire   [31:0] grp_fu_933_p2;
wire   [31:0] grp_fu_939_p2;
wire   [31:0] y_assign_2_fu_1034_p1;
wire   [31:0] z1_6_fu_1031_p1;
wire   [31:0] x_assign_1_fu_1040_p1;
wire   [31:0] grp_fu_650_p2;
wire   [31:0] x_assign_2_fu_1046_p1;
wire   [31:0] z1_5_fu_1028_p1;
wire   [31:0] y_assign_1_fu_1052_p1;
wire   [31:0] grp_fu_1058_p0;
wire   [13:0] grp_fu_1058_p1;
wire   [31:0] grp_fu_1063_p0;
wire   [13:0] grp_fu_1063_p1;
wire   [31:0] grp_fu_1068_p0;
wire   [13:0] grp_fu_1068_p1;
wire   [31:0] grp_fu_1073_p0;
wire   [13:0] grp_fu_1073_p1;
wire   [31:0] grp_fu_1078_p0;
wire   [13:0] grp_fu_1078_p1;
wire   [31:0] grp_fu_1083_p0;
wire   [11:0] grp_fu_1083_p1;
wire   [31:0] grp_fu_1088_p0;
wire   [11:0] grp_fu_1088_p1;
wire   [31:0] grp_fu_1093_p0;
wire   [13:0] grp_fu_1093_p1;
wire   [5:0] p_sum_fu_1098_p5;
wire   [31:0] tmp_3_fu_1114_p2;
wire   [31:0] tmp_12_fu_1128_p2;
wire   [31:0] z3_3_fu_1145_p1;
wire   [31:0] z1_3_fu_1142_p1;
wire   [31:0] z3_0_fu_1151_p1;
wire   [31:0] tmp_27_fu_1157_p2;
wire   [31:0] tmp_31_fu_1171_p2;
wire   [31:0] tmp_35_fu_1185_p2;
wire   [31:0] tmp_39_fu_1199_p2;
wire   [31:0] z3_2_fu_1216_p1;
wire   [31:0] z1_2_fu_1213_p1;
wire   [31:0] z3_1_fu_1221_p1;
wire   [31:0] tmp_41_fu_1229_p1;
wire   [31:0] z3_7_fu_1226_p1;
wire   [31:0] tmp_42_fu_1235_p1;
wire   [31:0] tmp_43_fu_1244_p1;
wire   [31:0] z3_6_fu_1241_p1;
wire   [31:0] tmp_44_fu_1250_p1;
wire   [31:0] tmp_45_fu_1259_p1;
wire   [31:0] z3_5_fu_1256_p1;
wire   [31:0] tmp_46_fu_1265_p1;
wire   [31:0] tmp_47_fu_1274_p1;
wire   [31:0] z3_4_fu_1271_p1;
wire   [31:0] tmp_48_fu_1280_p1;
wire   [5:0] row_1_cast1_fu_1302_p1;
wire   [5:0] tmp_71_fu_1322_p2;
wire   [5:0] tmp_72_fu_1328_p2;
wire   [31:0] grp_fu_1338_p0;
wire   [14:0] grp_fu_1338_p1;
wire   [31:0] grp_fu_1344_p0;
wire   [14:0] grp_fu_1344_p1;
wire   [31:0] grp_fu_1350_p0;
wire   [13:0] grp_fu_1350_p1;
wire   [31:0] grp_fu_1355_p0;
wire   [14:0] grp_fu_1355_p1;
wire   [31:0] grp_fu_1360_p0;
wire   [14:0] grp_fu_1360_p1;
wire   [31:0] grp_fu_1365_p0;
wire   [13:0] grp_fu_1365_p1;
wire   [31:0] grp_fu_1338_p2;
wire   [31:0] grp_fu_1344_p2;
wire   [31:0] y_assign_5_fu_1396_p1;
wire   [31:0] z1_6_1_fu_1393_p1;
wire   [31:0] x_assign_4_fu_1402_p1;
wire   [31:0] grp_fu_662_p2;
wire   [31:0] x_assign_5_fu_1408_p1;
wire   [31:0] z1_5_1_fu_1390_p1;
wire   [31:0] y_assign_4_fu_1414_p1;
wire   [31:0] grp_fu_1420_p0;
wire   [13:0] grp_fu_1420_p1;
wire   [31:0] grp_fu_1425_p0;
wire   [13:0] grp_fu_1425_p1;
wire   [31:0] grp_fu_1430_p0;
wire   [13:0] grp_fu_1430_p1;
wire   [31:0] grp_fu_1435_p0;
wire   [13:0] grp_fu_1435_p1;
wire   [31:0] grp_fu_1440_p0;
wire   [13:0] grp_fu_1440_p1;
wire   [31:0] grp_fu_1445_p0;
wire   [11:0] grp_fu_1445_p1;
wire   [31:0] grp_fu_1450_p0;
wire   [11:0] grp_fu_1450_p1;
wire   [31:0] grp_fu_1455_p0;
wire   [13:0] grp_fu_1455_p1;
wire   [31:0] tmp_13_fu_1460_p2;
wire   [31:0] tmp_18_fu_1474_p2;
wire   [31:0] z3_3_1_fu_1491_p1;
wire   [31:0] z1_3_1_fu_1488_p1;
wire   [31:0] z3_0_1_fu_1497_p1;
wire   [31:0] tmp_36_fu_1503_p2;
wire   [31:0] tmp_53_fu_1517_p2;
wire   [31:0] tmp_57_fu_1531_p2;
wire   [31:0] tmp_61_fu_1545_p2;
wire   [31:0] z3_2_1_fu_1562_p1;
wire   [31:0] z1_2_1_fu_1559_p1;
wire   [31:0] z3_1_1_fu_1567_p1;
wire   [31:0] tmp_63_fu_1575_p1;
wire   [31:0] z3_7_1_fu_1572_p1;
wire   [31:0] tmp_64_fu_1581_p1;
wire   [31:0] tmp_65_fu_1590_p1;
wire   [31:0] z3_6_1_fu_1587_p1;
wire   [31:0] tmp_66_fu_1596_p1;
wire   [31:0] tmp_67_fu_1605_p1;
wire   [31:0] z3_5_1_fu_1602_p1;
wire   [31:0] tmp_68_fu_1611_p1;
wire   [31:0] tmp_69_fu_1620_p1;
wire   [31:0] z3_4_1_fu_1617_p1;
wire   [31:0] tmp_70_fu_1626_p1;
wire   [5:0] row_2_cast_fu_1637_p1;
wire   [5:0] tmp_95_fu_1653_p2;
wire   [0:0] tmp_89_fu_1664_p3;
wire   [5:0] tmp_fu_1676_p0;
wire   [5:0] tmp_fu_1676_p2;
wire   [31:0] tmp_cast_fu_1682_p1;
wire   [31:0] tmp_90_fu_1686_p2;
wire   [26:0] r_fu_1705_p0;
wire   [26:0] r_fu_1705_p2;
wire   [18:0] tmp_93_fu_1717_p4;
wire   [0:0] icmp_fu_1727_p2;
wire   [7:0] tmp_94_fu_1733_p1;
wire   [6:0] i_6_cast_fu_1756_p1;
wire   [6:0] tmp_i_fu_1760_p2;
wire   [6:0] tmp332338_i_fu_1771_p5;
wire   [6:0] tmp333339_i_fu_1788_p5;
wire   [6:0] tmp335340_i_fu_1805_p5;
wire   [31:0] p_Result_s_fu_1834_p1;
wire   [23:0] tmp_87_fu_1837_p4;
wire    grp_fu_933_ce;
wire    grp_fu_939_ce;
wire    grp_fu_988_ce;
wire    grp_fu_993_ce;
wire    grp_fu_998_ce;
wire    grp_fu_1003_ce;
wire    grp_fu_1058_ce;
wire    grp_fu_1063_ce;
wire    grp_fu_1068_ce;
wire    grp_fu_1073_ce;
wire    grp_fu_1078_ce;
wire    grp_fu_1083_ce;
wire    grp_fu_1088_ce;
wire    grp_fu_1093_ce;
wire    grp_fu_1338_ce;
wire    grp_fu_1344_ce;
wire    grp_fu_1350_ce;
wire    grp_fu_1355_ce;
wire    grp_fu_1360_ce;
wire    grp_fu_1365_ce;
wire    grp_fu_1420_ce;
wire    grp_fu_1425_ce;
wire    grp_fu_1430_ce;
wire    grp_fu_1435_ce;
wire    grp_fu_1440_ce;
wire    grp_fu_1445_ce;
wire    grp_fu_1450_ce;
wire    grp_fu_1455_ce;
reg   [5:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 6'b000000;
parameter    ap_ST_st2_fsm_1 = 6'b000001;
parameter    ap_ST_st3_fsm_2 = 6'b000010;
parameter    ap_ST_st4_fsm_3 = 6'b000011;
parameter    ap_ST_st5_fsm_4 = 6'b000100;
parameter    ap_ST_st6_fsm_5 = 6'b000101;
parameter    ap_ST_st7_fsm_6 = 6'b000110;
parameter    ap_ST_st8_fsm_7 = 6'b000111;
parameter    ap_ST_st9_fsm_8 = 6'b001000;
parameter    ap_ST_st10_fsm_9 = 6'b001001;
parameter    ap_ST_st11_fsm_10 = 6'b001010;
parameter    ap_ST_st12_fsm_11 = 6'b001011;
parameter    ap_ST_st13_fsm_12 = 6'b001100;
parameter    ap_ST_st14_fsm_13 = 6'b001101;
parameter    ap_ST_st15_fsm_14 = 6'b001110;
parameter    ap_ST_st16_fsm_15 = 6'b001111;
parameter    ap_ST_st17_fsm_16 = 6'b010000;
parameter    ap_ST_st18_fsm_17 = 6'b010001;
parameter    ap_ST_st19_fsm_18 = 6'b010010;
parameter    ap_ST_st20_fsm_19 = 6'b010011;
parameter    ap_ST_st21_fsm_20 = 6'b010100;
parameter    ap_ST_st22_fsm_21 = 6'b010101;
parameter    ap_ST_st23_fsm_22 = 6'b010110;
parameter    ap_ST_st24_fsm_23 = 6'b010111;
parameter    ap_ST_st25_fsm_24 = 6'b011000;
parameter    ap_ST_st26_fsm_25 = 6'b011001;
parameter    ap_ST_st27_fsm_26 = 6'b011010;
parameter    ap_ST_st28_fsm_27 = 6'b011011;
parameter    ap_ST_st29_fsm_28 = 6'b011100;
parameter    ap_ST_st30_fsm_29 = 6'b011101;
parameter    ap_ST_st31_fsm_30 = 6'b011110;
parameter    ap_ST_st32_fsm_31 = 6'b011111;
parameter    ap_ST_st33_fsm_32 = 6'b100000;
parameter    ap_ST_st34_fsm_33 = 6'b100001;
parameter    ap_ST_st35_fsm_34 = 6'b100010;
parameter    ap_ST_st36_fsm_35 = 6'b100011;
parameter    ap_ST_st37_fsm_36 = 6'b100100;
parameter    ap_ST_st38_fsm_37 = 6'b100101;
parameter    ap_ST_st39_fsm_38 = 6'b100110;
parameter    ap_ST_st40_fsm_39 = 6'b100111;
parameter    ap_ST_st41_fsm_40 = 6'b101000;
parameter    ap_ST_st42_fsm_41 = 6'b101001;
parameter    ap_ST_st43_fsm_42 = 6'b101010;
parameter    ap_ST_st44_fsm_43 = 6'b101011;
parameter    ap_ST_st45_fsm_44 = 6'b101100;
parameter    ap_ST_st46_fsm_45 = 6'b101101;
parameter    ap_ST_st47_fsm_46 = 6'b101110;
parameter    ap_ST_st48_fsm_47 = 6'b101111;
parameter    ap_ST_st49_fsm_48 = 6'b110000;
parameter    ap_ST_st50_fsm_49 = 6'b110001;
parameter    ap_ST_st51_fsm_50 = 6'b110010;
parameter    ap_ST_st52_fsm_51 = 6'b110011;
parameter    ap_ST_st53_fsm_52 = 6'b110100;
parameter    ap_ST_st54_fsm_53 = 6'b110101;
parameter    ap_ST_st55_fsm_54 = 6'b110110;
parameter    ap_ST_st56_fsm_55 = 6'b110111;
parameter    ap_ST_st57_fsm_56 = 6'b111000;
parameter    ap_ST_st58_fsm_57 = 6'b111001;
parameter    ap_ST_st59_fsm_58 = 6'b111010;
parameter    ap_ST_st60_fsm_59 = 6'b111011;
parameter    ap_ST_st61_fsm_60 = 6'b111100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv32_4 = 32'b00000000000000000000000000000100;
parameter    ap_const_lv32_6 = 32'b00000000000000000000000000000110;
parameter    ap_const_lv32_2 = 32'b00000000000000000000000000000010;
parameter    ap_const_lv32_1 = 32'b00000000000000000000000000000001;
parameter    ap_const_lv32_7 = 32'b00000000000000000000000000000111;
parameter    ap_const_lv32_3 = 32'b00000000000000000000000000000011;
parameter    ap_const_lv32_5 = 32'b00000000000000000000000000000101;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv7_1 = 7'b0000001;
parameter    ap_const_lv6_20 = 6'b100000;
parameter    ap_const_lv6_1 = 6'b000001;
parameter    ap_const_lv32_10 = 32'b00000000000000000000000000010000;
parameter    ap_const_lv32_1F = 32'b00000000000000000000000000011111;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_1 = 4'b0001;
parameter    ap_const_lv6_3 = 6'b000011;
parameter    ap_const_lv6_5 = 6'b000101;
parameter    ap_const_lv19_3 = 19'b0000000000000000011;
parameter    ap_const_lv6_6 = 6'b000110;
parameter    ap_const_lv6_2 = 6'b000010;
parameter    ap_const_lv32_5A82 = 32'b00000000000000000101101010000010;
parameter    ap_const_lv6_7 = 6'b000111;
parameter    ap_const_lv32_22A3 = 32'b00000000000000000010001010100011;
parameter    ap_const_lv32_539F = 32'b00000000000000000101001110011111;
parameter    ap_const_lv32_E = 32'b00000000000000000000000000001110;
parameter    ap_const_lv32_3537 = 32'b00000000000000000011010100110111;
parameter    ap_const_lv32_238E = 32'b00000000000000000010001110001110;
parameter    ap_const_lv32_3EC5 = 32'b00000000000000000011111011000101;
parameter    ap_const_lv32_C7C = 32'b00000000000000000000110001111100;
parameter    ap_const_lv6_4 = 6'b000100;
parameter    ap_const_lv27_80 = 27'b000000000000000000010000000;
parameter    ap_const_lv27_0 = 27'b000000000000000000000000000;
parameter    ap_const_lv32_8 = 32'b00000000000000000000000000001000;
parameter    ap_const_lv32_1A = 32'b00000000000000000000000000011010;
parameter    ap_const_lv19_1 = 19'b0000000000000000001;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv7_2 = 7'b0000010;
parameter    ap_const_lv7_3 = 7'b0000011;
parameter    ap_const_lv5_10 = 5'b10000;
parameter    ap_const_lv5_1 = 5'b00001;
parameter    ap_true = 1'b1;


IDCT_thread_Y #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
Y_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( Y_address0 ),
    .ce0( Y_ce0 ),
    .we0( Y_we0 ),
    .d0( Y_d0 ),
    .q0( Y_q0 ),
    .address1( Y_address1 ),
    .ce1( Y_ce1 ),
    .we1( Y_we1 ),
    .d1( Y_d1 ),
    .q1( Y_q1 )
);

IDCT_thread_in #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
in_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( in_address0 ),
    .ce0( in_ce0 ),
    .we0( in_we0 ),
    .d0( in_d0 ),
    .q0( in_q0 ),
    .address1( in_address1 ),
    .ce1( in_ce1 ),
    .we1( in_we1 ),
    .d1( in_d1 )
);

IDCT_thread_Idct #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
Idct_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( Idct_address0 ),
    .ce0( Idct_ce0 ),
    .we0( Idct_we0 ),
    .d0( Idct_d0 ),
    .q0( Idct_q0 ),
    .address1( Idct_address1 ),
    .ce1( Idct_ce1 ),
    .q1( Idct_q1 )
);

IDCT_thread_Yc #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
Yc_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( Yc_address0 ),
    .ce0( Yc_ce0 ),
    .we0( Yc_we0 ),
    .d0( Yc_d0 ),
    .q0( Yc_q0 ),
    .address1( Yc_address1 ),
    .ce1( Yc_ce1 ),
    .we1( Yc_we1 ),
    .d1( Yc_d1 ),
    .q1( Yc_q1 )
);

IDCT_mul_32s_15ns_32_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_15ns_32_3_U1(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_933_p0 ),
    .din1( grp_fu_933_p1 ),
    .ce( grp_fu_933_ce ),
    .dout( grp_fu_933_p2 )
);

IDCT_mul_32s_15ns_32_3 #(
    .ID( 2 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_15ns_32_3_U2(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_939_p0 ),
    .din1( grp_fu_939_p1 ),
    .ce( grp_fu_939_ce ),
    .dout( grp_fu_939_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 3 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U3(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_988_p0 ),
    .din1( grp_fu_988_p1 ),
    .ce( grp_fu_988_ce ),
    .dout( grp_fu_988_p2 )
);

IDCT_mul_32s_15ns_32_3 #(
    .ID( 4 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_15ns_32_3_U4(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_993_p0 ),
    .din1( grp_fu_993_p1 ),
    .ce( grp_fu_993_ce ),
    .dout( grp_fu_993_p2 )
);

IDCT_mul_32s_15ns_32_3 #(
    .ID( 5 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_15ns_32_3_U5(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_998_p0 ),
    .din1( grp_fu_998_p1 ),
    .ce( grp_fu_998_ce ),
    .dout( grp_fu_998_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 6 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U6(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1003_p0 ),
    .din1( grp_fu_1003_p1 ),
    .ce( grp_fu_1003_ce ),
    .dout( grp_fu_1003_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 7 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U7(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1058_p0 ),
    .din1( grp_fu_1058_p1 ),
    .ce( grp_fu_1058_ce ),
    .dout( grp_fu_1058_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 8 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U8(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1063_p0 ),
    .din1( grp_fu_1063_p1 ),
    .ce( grp_fu_1063_ce ),
    .dout( grp_fu_1063_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 9 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U9(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1068_p0 ),
    .din1( grp_fu_1068_p1 ),
    .ce( grp_fu_1068_ce ),
    .dout( grp_fu_1068_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 10 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U10(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1073_p0 ),
    .din1( grp_fu_1073_p1 ),
    .ce( grp_fu_1073_ce ),
    .dout( grp_fu_1073_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 11 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U11(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1078_p0 ),
    .din1( grp_fu_1078_p1 ),
    .ce( grp_fu_1078_ce ),
    .dout( grp_fu_1078_p2 )
);

IDCT_mul_32s_12ns_32_3 #(
    .ID( 12 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_12ns_32_3_U12(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1083_p0 ),
    .din1( grp_fu_1083_p1 ),
    .ce( grp_fu_1083_ce ),
    .dout( grp_fu_1083_p2 )
);

IDCT_mul_32s_12ns_32_3 #(
    .ID( 13 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_12ns_32_3_U13(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1088_p0 ),
    .din1( grp_fu_1088_p1 ),
    .ce( grp_fu_1088_ce ),
    .dout( grp_fu_1088_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 14 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U14(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1093_p0 ),
    .din1( grp_fu_1093_p1 ),
    .ce( grp_fu_1093_ce ),
    .dout( grp_fu_1093_p2 )
);

IDCT_mul_32s_15ns_32_3 #(
    .ID( 15 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_15ns_32_3_U15(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1338_p0 ),
    .din1( grp_fu_1338_p1 ),
    .ce( grp_fu_1338_ce ),
    .dout( grp_fu_1338_p2 )
);

IDCT_mul_32s_15ns_32_3 #(
    .ID( 16 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_15ns_32_3_U16(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1344_p0 ),
    .din1( grp_fu_1344_p1 ),
    .ce( grp_fu_1344_ce ),
    .dout( grp_fu_1344_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 17 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U17(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1350_p0 ),
    .din1( grp_fu_1350_p1 ),
    .ce( grp_fu_1350_ce ),
    .dout( grp_fu_1350_p2 )
);

IDCT_mul_32s_15ns_32_3 #(
    .ID( 18 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_15ns_32_3_U18(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1355_p0 ),
    .din1( grp_fu_1355_p1 ),
    .ce( grp_fu_1355_ce ),
    .dout( grp_fu_1355_p2 )
);

IDCT_mul_32s_15ns_32_3 #(
    .ID( 19 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_15ns_32_3_U19(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1360_p0 ),
    .din1( grp_fu_1360_p1 ),
    .ce( grp_fu_1360_ce ),
    .dout( grp_fu_1360_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 20 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U20(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1365_p0 ),
    .din1( grp_fu_1365_p1 ),
    .ce( grp_fu_1365_ce ),
    .dout( grp_fu_1365_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 21 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U21(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1420_p0 ),
    .din1( grp_fu_1420_p1 ),
    .ce( grp_fu_1420_ce ),
    .dout( grp_fu_1420_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 22 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U22(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1425_p0 ),
    .din1( grp_fu_1425_p1 ),
    .ce( grp_fu_1425_ce ),
    .dout( grp_fu_1425_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 23 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U23(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1430_p0 ),
    .din1( grp_fu_1430_p1 ),
    .ce( grp_fu_1430_ce ),
    .dout( grp_fu_1430_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 24 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U24(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1435_p0 ),
    .din1( grp_fu_1435_p1 ),
    .ce( grp_fu_1435_ce ),
    .dout( grp_fu_1435_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 25 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U25(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1440_p0 ),
    .din1( grp_fu_1440_p1 ),
    .ce( grp_fu_1440_ce ),
    .dout( grp_fu_1440_p2 )
);

IDCT_mul_32s_12ns_32_3 #(
    .ID( 26 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_12ns_32_3_U26(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1445_p0 ),
    .din1( grp_fu_1445_p1 ),
    .ce( grp_fu_1445_ce ),
    .dout( grp_fu_1445_p2 )
);

IDCT_mul_32s_12ns_32_3 #(
    .ID( 27 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_12ns_32_3_U27(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1450_p0 ),
    .din1( grp_fu_1450_p1 ),
    .ce( grp_fu_1450_ce ),
    .dout( grp_fu_1450_p2 )
);

IDCT_mul_32s_14ns_32_3 #(
    .ID( 28 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
IDCT_mul_32s_14ns_32_3_U28(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1455_p0 ),
    .din1( grp_fu_1455_p1 ),
    .ce( grp_fu_1455_ce ),
    .dout( grp_fu_1455_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st56_fsm_55 == ap_CS_fsm)) begin
        Idct_addr_1_reg_2470 <= tmp332338_i_cast_fu_1783_p1;
    end
    if ((ap_ST_st56_fsm_55 == ap_CS_fsm)) begin
        Idct_addr_2_reg_2475 <= tmp333339_i_cast_fu_1800_p1;
    end
    if ((ap_ST_st56_fsm_55 == ap_CS_fsm)) begin
        Idct_addr_3_reg_2480 <= tmp335340_i_cast_fu_1817_p1;
    end
    if ((ap_ST_st56_fsm_55 == ap_CS_fsm)) begin
        Idct_addr_4_reg_2485[2] <= tmp_i_cast_fu_1766_p1[2];
        Idct_addr_4_reg_2485[3] <= tmp_i_cast_fu_1766_p1[3];
        Idct_addr_4_reg_2485[4] <= tmp_i_cast_fu_1766_p1[4];
        Idct_addr_4_reg_2485[5] <= tmp_i_cast_fu_1766_p1[5];
    end
    if ((ap_ST_st58_fsm_57 == ap_CS_fsm)) begin
        Idct_load_1_reg_2506 <= Idct_q1;
    end
    if ((ap_ST_st58_fsm_57 == ap_CS_fsm)) begin
        Idct_load_reg_2501 <= Idct_q0;
    end
    if (((ap_ST_st12_fsm_11 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_262_p2))) begin
        NBLOCKS_fu_206 <= ReadDataPort_0;
    end else if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        NBLOCKS_fu_206 <= ap_const_lv32_0;
    end
    if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        Y_addr_1_reg_2040 <= p_sum1_cast_fu_908_p1;
    end
    if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        Y_addr_2_reg_2045 <= p_sum2_cast_fu_928_p1;
    end
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        Y_addr_3_reg_2067 <= p_sum3_cast_fu_963_p1;
    end
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        Y_addr_4_reg_2073 <= p_sum4_cast_fu_983_p1;
    end
    if (((ap_ST_st21_fsm_20 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_fu_816_p2))) begin
        Y_addr_5_reg_2028 <= p_sum5_cast_fu_853_p1;
    end
    if (((ap_ST_st21_fsm_20 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_fu_816_p2))) begin
        Y_addr_6_reg_2034 <= p_sum6_cast_fu_873_p1;
    end
    if (((ap_ST_st21_fsm_20 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_fu_816_p2))) begin
        Y_addr_9_reg_2022[3] <= tmp_2_cast_reg_1999[3];
        Y_addr_9_reg_2022[4] <= tmp_2_cast_reg_1999[4];
        Y_addr_9_reg_2022[5] <= tmp_2_cast_reg_1999[5];
    end
    if ((ap_ST_st29_fsm_28 == ap_CS_fsm)) begin
        Y_addr_reg_2133 <= p_sum_cast_fu_1109_p1;
    end
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        Y_load_7_reg_2055 <= Y_q0;
    end
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        Y_load_8_reg_2061 <= Y_q1;
    end
    if ((ap_ST_st41_fsm_40 == ap_CS_fsm)) begin
        Yc_load_2_reg_2271 <= Yc_q0;
    end
    if ((ap_ST_st41_fsm_40 == ap_CS_fsm)) begin
        Yc_load_8_reg_2277 <= Yc_q1;
    end
    if ((ap_ST_st15_fsm_14 == ap_CS_fsm)) begin
        block_1_reg_1949 <= block_1_fu_721_p2;
    end
    if (((ap_ST_st56_fsm_55 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond6_fu_1822_p2))) begin
        block_reg_536 <= block_1_reg_1949;
    end else if (((ap_ST_st11_fsm_10 == ap_CS_fsm) & (((tmp_4_reg_1923 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_8_fu_696_p2)) | (~(ap_const_lv1_0 == tmp_8_fu_696_p2) & ~(ap_const_lv1_0 == indvar_phi_fu_529_p4))))) begin
        block_reg_536 <= ap_const_lv32_0;
    end
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_790_p2))) begin
        column_1_reg_569 <= ap_const_lv4_0;
    end else if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        column_1_reg_569 <= column_2_reg_2007;
    end
    if ((ap_ST_st21_fsm_20 == ap_CS_fsm)) begin
        column_2_reg_2007 <= column_2_fu_822_p2;
    end
    if ((ap_ST_st36_fsm_35 == ap_CS_fsm)) begin
        column_3_reg_2248 <= column_3_fu_1296_p2;
    end
    if ((ap_ST_st36_fsm_35 == ap_CS_fsm)) begin
        column_cast_reg_2239[0] <= column_cast_fu_1286_p1[0];
        column_cast_reg_2239[1] <= column_cast_fu_1286_p1[1];
        column_cast_reg_2239[2] <= column_cast_fu_1286_p1[2];
        column_cast_reg_2239[3] <= column_cast_fu_1286_p1[3];
    end
    if (((ap_ST_st52_fsm_51 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_1641_p2))) begin
        column_reg_580 <= column_3_reg_2248;
    end else if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_790_p2))) begin
        column_reg_580 <= ap_const_lv4_0;
    end
    if ((ap_ST_st16_fsm_15 == ap_CS_fsm)) begin
        i_1_reg_1967 <= i_1_fu_764_p2;
    end
    if (((ap_ST_st36_fsm_35 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond3_fu_1290_p2))) begin
        i_2_reg_613 <= ap_const_lv5_0;
    end else if ((ap_ST_st61_fsm_60 == ap_CS_fsm)) begin
        i_2_reg_613 <= i_3_reg_2493;
    end
    if ((ap_ST_st56_fsm_55 == ap_CS_fsm)) begin
        i_3_reg_2493 <= i_3_fu_1828_p2;
    end
    if ((ap_ST_st19_fsm_18 == ap_CS_fsm)) begin
        i_reg_547 <= i_1_reg_1967;
    end else if (((ap_ST_st15_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_716_p2))) begin
        i_reg_547 <= ap_const_lv6_0;
    end
    if ((ap_ST_st16_fsm_15 == ap_CS_fsm)) begin
        in_addr_1_reg_1959[1] <= ptData3_0_rec_i_cast_fu_737_p1[1];
        in_addr_1_reg_1959[2] <= ptData3_0_rec_i_cast_fu_737_p1[2];
        in_addr_1_reg_1959[3] <= ptData3_0_rec_i_cast_fu_737_p1[3];
        in_addr_1_reg_1959[4] <= ptData3_0_rec_i_cast_fu_737_p1[4];
        in_addr_1_reg_1959[5] <= ptData3_0_rec_i_cast_fu_737_p1[5];
    end
    if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        indvar1_reg_514 <= ap_const_lv1_0;
    end else if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        indvar1_reg_514 <= indvar_next1_reg_1918;
    end
    if ((ap_ST_st7_fsm_6 == ap_CS_fsm)) begin
        indvar_next1_reg_1918 <= indvar_next1_fu_673_p2;
    end
    if (((ap_ST_st11_fsm_10 == ap_CS_fsm) & ~(tmp_4_reg_1923 == ap_const_lv1_0))) begin
        indvar_next_reg_1930 <= indvar_next_fu_690_p2;
    end
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(indvar1_phi_fu_518_p4 == ap_const_lv1_0) & ~(tmp_4_fu_679_p2 == ap_const_lv1_0))) begin
        indvar_reg_525 <= ap_const_lv1_0;
    end else if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        indvar_reg_525 <= indvar_next_reg_1930;
    end
    if ((ap_ST_st54_fsm_53 == ap_CS_fsm)) begin
        phitmp_reg_2465 <= phitmp_fu_1737_p3;
    end
    if ((ap_ST_st16_fsm_15 == ap_CS_fsm)) begin
        ptData3_0_sum238241_i_cast_reg_1954[0] <= ptData3_0_sum238241_i_cast_fu_754_p1[0];
        ptData3_0_sum238241_i_cast_reg_1954[1] <= ptData3_0_sum238241_i_cast_fu_754_p1[1];
        ptData3_0_sum238241_i_cast_reg_1954[2] <= ptData3_0_sum238241_i_cast_fu_754_p1[2];
        ptData3_0_sum238241_i_cast_reg_1954[3] <= ptData3_0_sum238241_i_cast_fu_754_p1[3];
        ptData3_0_sum238241_i_cast_reg_1954[4] <= ptData3_0_sum238241_i_cast_fu_754_p1[4];
        ptData3_0_sum238241_i_cast_reg_1954[5] <= ptData3_0_sum238241_i_cast_fu_754_p1[5];
        ptData3_0_sum238241_i_cast_reg_1954[6] <= ptData3_0_sum238241_i_cast_fu_754_p1[6];
    end
    if (((ap_ST_st23_fsm_22 == ap_CS_fsm) | (ap_ST_st26_fsm_25 == ap_CS_fsm) | (ap_ST_st30_fsm_29 == ap_CS_fsm))) begin
        reg_628 <= Y_q0;
    end
    if (((ap_ST_st23_fsm_22 == ap_CS_fsm) | (ap_ST_st26_fsm_25 == ap_CS_fsm) | (ap_ST_st30_fsm_29 == ap_CS_fsm))) begin
        reg_632 <= Y_q1;
    end
    if (((ap_ST_st39_fsm_38 == ap_CS_fsm) | (ap_ST_st42_fsm_41 == ap_CS_fsm) | (ap_ST_st46_fsm_45 == ap_CS_fsm))) begin
        reg_636 <= Yc_q0;
    end
    if (((ap_ST_st39_fsm_38 == ap_CS_fsm) | (ap_ST_st42_fsm_41 == ap_CS_fsm) | (ap_ST_st46_fsm_45 == ap_CS_fsm))) begin
        reg_640 <= Yc_q1;
    end
    if ((ap_ST_st37_fsm_36 == ap_CS_fsm)) begin
        row_1_cast_reg_2253[0] <= row_1_cast_fu_1306_p1[0];
        row_1_cast_reg_2253[1] <= row_1_cast_fu_1306_p1[1];
        row_1_cast_reg_2253[2] <= row_1_cast_fu_1306_p1[2];
        row_1_cast_reg_2253[3] <= row_1_cast_fu_1306_p1[3];
    end
    if (((ap_ST_st36_fsm_35 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_1290_p2))) begin
        row_1_reg_591 <= ap_const_lv4_0;
    end else if ((ap_ST_st38_fsm_37 == ap_CS_fsm)) begin
        row_1_reg_591 <= row_4_reg_2261;
    end
    if ((ap_ST_st55_fsm_54 == ap_CS_fsm)) begin
        row_2_reg_602 <= row_5_reg_2440;
    end else if ((ap_ST_st51_fsm_50 == ap_CS_fsm)) begin
        row_2_reg_602 <= ap_const_lv4_0;
    end
    if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        row_3_reg_1989 <= row_3_fu_796_p2;
    end
    if ((ap_ST_st37_fsm_36 == ap_CS_fsm)) begin
        row_4_reg_2261 <= row_4_fu_1316_p2;
    end
    if ((ap_ST_st52_fsm_51 == ap_CS_fsm)) begin
        row_5_reg_2440 <= row_5_fu_1647_p2;
    end
    if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        row_cast_reg_1975[0] <= row_cast_fu_786_p1[0];
        row_cast_reg_1975[1] <= row_cast_fu_786_p1[1];
        row_cast_reg_1975[2] <= row_cast_fu_786_p1[2];
        row_cast_reg_1975[3] <= row_cast_fu_786_p1[3];
    end
    if (((ap_ST_st16_fsm_15 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_758_p2))) begin
        row_reg_558 <= ap_const_lv4_0;
    end else if ((ap_ST_st35_fsm_34 == ap_CS_fsm)) begin
        row_reg_558 <= row_3_reg_1989;
    end
    if (((ap_ST_st11_fsm_10 == ap_CS_fsm) & (((tmp_4_reg_1923 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_8_fu_696_p2)) | (~(ap_const_lv1_0 == tmp_8_fu_696_p2) & ~(ap_const_lv1_0 == indvar_phi_fu_529_p4))))) begin
        tmp1_reg_1938[1] <= tmp1_fu_705_p2[1];
        tmp1_reg_1938[2] <= tmp1_fu_705_p2[2];
        tmp1_reg_1938[3] <= tmp1_fu_705_p2[3];
        tmp1_reg_1938[4] <= tmp1_fu_705_p2[4];
        tmp1_reg_1938[5] <= tmp1_fu_705_p2[5];
        tmp1_reg_1938[6] <= tmp1_fu_705_p2[6];
        tmp1_reg_1938[7] <= tmp1_fu_705_p2[7];
        tmp1_reg_1938[8] <= tmp1_fu_705_p2[8];
        tmp1_reg_1938[9] <= tmp1_fu_705_p2[9];
        tmp1_reg_1938[10] <= tmp1_fu_705_p2[10];
        tmp1_reg_1938[11] <= tmp1_fu_705_p2[11];
        tmp1_reg_1938[12] <= tmp1_fu_705_p2[12];
        tmp1_reg_1938[13] <= tmp1_fu_705_p2[13];
        tmp1_reg_1938[14] <= tmp1_fu_705_p2[14];
        tmp1_reg_1938[15] <= tmp1_fu_705_p2[15];
        tmp1_reg_1938[16] <= tmp1_fu_705_p2[16];
        tmp1_reg_1938[17] <= tmp1_fu_705_p2[17];
        tmp1_reg_1938[18] <= tmp1_fu_705_p2[18];
        tmp1_reg_1938[19] <= tmp1_fu_705_p2[19];
        tmp1_reg_1938[20] <= tmp1_fu_705_p2[20];
        tmp1_reg_1938[21] <= tmp1_fu_705_p2[21];
        tmp1_reg_1938[22] <= tmp1_fu_705_p2[22];
        tmp1_reg_1938[23] <= tmp1_fu_705_p2[23];
        tmp1_reg_1938[24] <= tmp1_fu_705_p2[24];
        tmp1_reg_1938[25] <= tmp1_fu_705_p2[25];
        tmp1_reg_1938[26] <= tmp1_fu_705_p2[26];
        tmp1_reg_1938[27] <= tmp1_fu_705_p2[27];
        tmp1_reg_1938[28] <= tmp1_fu_705_p2[28];
        tmp1_reg_1938[29] <= tmp1_fu_705_p2[29];
        tmp1_reg_1938[30] <= tmp1_fu_705_p2[30];
        tmp1_reg_1938[31] <= tmp1_fu_705_p2[31];
    end
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        tmp_10_reg_2123 <= grp_fu_998_p2;
    end
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        tmp_11_reg_2128 <= grp_fu_1003_p2;
    end
    if ((ap_ST_st45_fsm_44 == ap_CS_fsm)) begin
        tmp_14_reg_2337 <= {{tmp_13_fu_1460_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        tmp_15_reg_2327 <= grp_fu_1360_p2;
    end
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        tmp_16_reg_2332 <= grp_fu_1365_p2;
    end
    if ((ap_ST_st45_fsm_44 == ap_CS_fsm)) begin
        tmp_20_reg_2342 <= {{tmp_18_fu_1474_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st42_fsm_41 == ap_CS_fsm)) begin
        tmp_22_reg_2283 <= {{grp_fu_1338_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st42_fsm_41 == ap_CS_fsm)) begin
        tmp_24_reg_2288 <= {{grp_fu_1344_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st30_fsm_29 == ap_CS_fsm)) begin
        tmp_25_reg_2149 <= grp_fu_1058_p2;
    end
    if ((ap_ST_st30_fsm_29 == ap_CS_fsm)) begin
        tmp_26_reg_2154 <= grp_fu_1063_p2;
    end
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        tmp_28_reg_2347 <= grp_fu_1420_p2;
    end
    if ((ap_ST_st30_fsm_29 == ap_CS_fsm)) begin
        tmp_29_reg_2159 <= grp_fu_1068_p2;
    end
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_790_p2))) begin
        tmp_2_cast_reg_1999[3] <= tmp_2_cast_fu_808_p1[3];
        tmp_2_cast_reg_1999[4] <= tmp_2_cast_fu_808_p1[4];
        tmp_2_cast_reg_1999[5] <= tmp_2_cast_fu_808_p1[5];
    end
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_790_p2))) begin
        tmp_2_reg_1994[3] <= tmp_2_fu_802_p2[3];
        tmp_2_reg_1994[4] <= tmp_2_fu_802_p2[4];
        tmp_2_reg_1994[5] <= tmp_2_fu_802_p2[5];
    end
    if ((ap_ST_st30_fsm_29 == ap_CS_fsm)) begin
        tmp_30_reg_2164 <= grp_fu_1073_p2;
    end
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        tmp_32_reg_2352 <= grp_fu_1425_p2;
    end
    if ((ap_ST_st30_fsm_29 == ap_CS_fsm)) begin
        tmp_33_reg_2169 <= grp_fu_1078_p2;
    end
    if ((ap_ST_st30_fsm_29 == ap_CS_fsm)) begin
        tmp_34_reg_2174 <= grp_fu_1083_p2;
    end
    if ((ap_ST_st30_fsm_29 == ap_CS_fsm)) begin
        tmp_37_reg_2179 <= grp_fu_1088_p2;
    end
    if ((ap_ST_st30_fsm_29 == ap_CS_fsm)) begin
        tmp_38_reg_2184 <= grp_fu_1093_p2;
    end
    if ((ap_ST_st47_fsm_46 == ap_CS_fsm)) begin
        tmp_40_reg_2405 <= {{tmp_36_fu_1503_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if (((ap_ST_st21_fsm_20 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_fu_816_p2))) begin
        tmp_49_cast_reg_2012[0] <= tmp_49_cast_fu_833_p1[0];
        tmp_49_cast_reg_2012[1] <= tmp_49_cast_fu_833_p1[1];
        tmp_49_cast_reg_2012[2] <= tmp_49_cast_fu_833_p1[2];
        tmp_49_cast_reg_2012[3] <= tmp_49_cast_fu_833_p1[3];
        tmp_49_cast_reg_2012[4] <= tmp_49_cast_fu_833_p1[4];
        tmp_49_cast_reg_2012[5] <= tmp_49_cast_fu_833_p1[5];
    end
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(indvar1_phi_fu_518_p4 == ap_const_lv1_0))) begin
        tmp_4_reg_1923 <= tmp_4_fu_679_p2;
    end
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        tmp_50_reg_2357 <= grp_fu_1430_p2;
    end
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        tmp_52_reg_2362 <= grp_fu_1435_p2;
    end
    if ((ap_ST_st47_fsm_46 == ap_CS_fsm)) begin
        tmp_54_reg_2410 <= {{tmp_53_fu_1517_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        tmp_55_reg_2367 <= grp_fu_1440_p2;
    end
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        tmp_56_reg_2372 <= grp_fu_1445_p2;
    end
    if ((ap_ST_st47_fsm_46 == ap_CS_fsm)) begin
        tmp_58_reg_2415 <= {{tmp_57_fu_1531_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        tmp_59_reg_2377 <= grp_fu_1450_p2;
    end
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        tmp_60_reg_2382 <= grp_fu_1455_p2;
    end
    if ((ap_ST_st47_fsm_46 == ap_CS_fsm)) begin
        tmp_62_reg_2420 <= {{tmp_61_fu_1545_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        tmp_6_reg_2317 <= grp_fu_1350_p2;
    end
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        tmp_73_reg_2050 <= tmp_73_fu_945_p1;
    end
    if ((ap_ST_st29_fsm_28 == ap_CS_fsm)) begin
        tmp_76_reg_2139 <= {{tmp_3_fu_1114_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st29_fsm_28 == ap_CS_fsm)) begin
        tmp_77_reg_2144 <= {{tmp_12_fu_1128_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        tmp_7_reg_2322 <= grp_fu_1355_p2;
    end
    if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        tmp_81_reg_2079 <= {{grp_fu_933_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        tmp_83_reg_2084 <= {{grp_fu_939_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st31_fsm_30 == ap_CS_fsm)) begin
        tmp_84_reg_2207 <= {{tmp_27_fu_1157_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st31_fsm_30 == ap_CS_fsm)) begin
        tmp_85_reg_2212 <= {{tmp_31_fu_1171_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st31_fsm_30 == ap_CS_fsm)) begin
        tmp_86_reg_2217 <= {{tmp_35_fu_1185_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st31_fsm_30 == ap_CS_fsm)) begin
        tmp_88_reg_2222 <= {{tmp_39_fu_1199_p2[ap_const_lv32_1F : ap_const_lv32_E]}};
    end
    if ((ap_ST_st53_fsm_52 == ap_CS_fsm)) begin
        tmp_91_reg_2455 <= {{tmp_90_fu_1686_p2[ap_const_lv32_1F : ap_const_lv32_6]}};
    end
    if ((ap_ST_st54_fsm_53 == ap_CS_fsm)) begin
        tmp_92_reg_2460 <= tmp_92_fu_1711_p2;
    end
    if (((ap_ST_st52_fsm_51 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_1641_p2))) begin
        tmp_96_reg_2450 <= tmp_96_fu_1659_p2;
    end
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        tmp_9_reg_2113 <= grp_fu_988_p2;
    end
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        tmp_s_reg_2118 <= grp_fu_993_p2;
    end
    if (((ap_const_lv1_0 == grp_wireread_fu_262_p2) & (ap_ST_st8_fsm_7 == ap_CS_fsm))) begin
        uiCommand_fu_210 <= ReadDataPort_0;
    end
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        x_assign_1_reg_2095 <= x_assign_1_fu_1040_p2;
    end
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        x_assign_2_reg_2101 <= x_assign_2_fu_1046_p2;
    end
    if ((ap_ST_st43_fsm_42 == ap_CS_fsm)) begin
        x_assign_4_reg_2299 <= x_assign_4_fu_1402_p2;
    end
    if ((ap_ST_st43_fsm_42 == ap_CS_fsm)) begin
        x_assign_5_reg_2305 <= x_assign_5_fu_1408_p2;
    end
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        y_assign_1_reg_2107 <= y_assign_1_fu_1052_p2;
    end
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        y_assign_2_reg_2089 <= y_assign_2_fu_1034_p2;
    end
    if ((ap_ST_st43_fsm_42 == ap_CS_fsm)) begin
        y_assign_4_reg_2311 <= y_assign_4_fu_1414_p2;
    end
    if ((ap_ST_st43_fsm_42 == ap_CS_fsm)) begin
        y_assign_5_reg_2293 <= y_assign_5_fu_1396_p2;
    end
    if ((ap_ST_st47_fsm_46 == ap_CS_fsm)) begin
        z1_1_1_reg_2387 <= grp_fu_656_p2;
    end
    if ((ap_ST_st31_fsm_30 == ap_CS_fsm)) begin
        z1_1_reg_2189 <= grp_fu_644_p2;
    end
    if ((ap_ST_st47_fsm_46 == ap_CS_fsm)) begin
        z3_0_1_reg_2399 <= z3_0_1_fu_1497_p2;
    end
    if ((ap_ST_st31_fsm_30 == ap_CS_fsm)) begin
        z3_0_reg_2201 <= z3_0_fu_1151_p2;
    end
    if ((ap_ST_st48_fsm_47 == ap_CS_fsm)) begin
        z3_1_1_reg_2431 <= z3_1_1_fu_1567_p2;
    end
    if ((ap_ST_st32_fsm_31 == ap_CS_fsm)) begin
        z3_1_reg_2233 <= z3_1_fu_1221_p2;
    end
    if ((ap_ST_st48_fsm_47 == ap_CS_fsm)) begin
        z3_2_1_reg_2425 <= z3_2_1_fu_1562_p2;
    end
    if ((ap_ST_st32_fsm_31 == ap_CS_fsm)) begin
        z3_2_reg_2227 <= z3_2_fu_1216_p2;
    end
    if ((ap_ST_st47_fsm_46 == ap_CS_fsm)) begin
        z3_3_1_reg_2393 <= z3_3_1_fu_1491_p2;
    end
    if ((ap_ST_st31_fsm_30 == ap_CS_fsm)) begin
        z3_3_reg_2195 <= z3_3_fu_1145_p2;
    end
end

/// Idct_address0 assign process. ///
always @ (ap_CS_fsm or Idct_addr_2_reg_2475 or Idct_addr_4_reg_2485 or tmp_107_cast_fu_1752_p1 or grp_wireread_fu_288_p2)
begin
    if ((ap_ST_st55_fsm_54 == ap_CS_fsm)) begin
        Idct_address0 = tmp_107_cast_fu_1752_p1;
    end else if ((ap_ST_st58_fsm_57 == ap_CS_fsm)) begin
        Idct_address0 = Idct_addr_2_reg_2475;
    end else if (((ap_ST_st57_fsm_56 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_288_p2))) begin
        Idct_address0 = Idct_addr_4_reg_2485;
    end else begin
        Idct_address0 = tmp_107_cast_fu_1752_p1;
    end
end

/// Idct_address1 assign process. ///
always @ (ap_CS_fsm or Idct_addr_1_reg_2470 or Idct_addr_3_reg_2480 or grp_wireread_fu_288_p2)
begin
    if ((ap_ST_st58_fsm_57 == ap_CS_fsm)) begin
        Idct_address1 = Idct_addr_1_reg_2470;
    end else if (((ap_ST_st57_fsm_56 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_288_p2))) begin
        Idct_address1 = Idct_addr_3_reg_2480;
    end else begin
        Idct_address1 = Idct_addr_3_reg_2480;
    end
end

/// Idct_ce0 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_288_p2)
begin
    if (((ap_ST_st58_fsm_57 == ap_CS_fsm) | (ap_ST_st55_fsm_54 == ap_CS_fsm) | ((ap_ST_st57_fsm_56 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_288_p2)))) begin
        Idct_ce0 = ap_const_logic_1;
    end else begin
        Idct_ce0 = ap_const_logic_0;
    end
end

/// Idct_ce1 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_288_p2)
begin
    if (((ap_ST_st58_fsm_57 == ap_CS_fsm) | ((ap_ST_st57_fsm_56 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_288_p2)))) begin
        Idct_ce1 = ap_const_logic_1;
    end else begin
        Idct_ce1 = ap_const_logic_0;
    end
end

/// Idct_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st55_fsm_54 == ap_CS_fsm)) begin
        Idct_we0 = ap_const_logic_1;
    end else begin
        Idct_we0 = ap_const_logic_0;
    end
end

/// ReadEnablePort_0 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_262_p2)
begin
    if (((ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st13_fsm_12 == ap_CS_fsm))) begin
        ReadEnablePort_0 = ap_const_lv1_0;
    end else if ((((ap_ST_st12_fsm_11 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_262_p2)) | ((ap_const_lv1_0 == grp_wireread_fu_262_p2) & (ap_ST_st8_fsm_7 == ap_CS_fsm)))) begin
        ReadEnablePort_0 = ap_const_lv1_1;
    end else begin
        ReadEnablePort_0 = ap_const_lv1_1;
    end
end

/// ReadEnablePort_0_ap_vld assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_262_p2)
begin
    if ((((ap_ST_st12_fsm_11 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_262_p2)) | ((ap_const_lv1_0 == grp_wireread_fu_262_p2) & (ap_ST_st8_fsm_7 == ap_CS_fsm)) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st13_fsm_12 == ap_CS_fsm))) begin
        ReadEnablePort_0_ap_vld = ap_const_logic_1;
    end else begin
        ReadEnablePort_0_ap_vld = ap_const_logic_0;
    end
end

/// ReadEnablePort_1 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_275_p2)
begin
    if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
        ReadEnablePort_1 = ap_const_lv1_0;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_275_p2))) begin
        ReadEnablePort_1 = ap_const_lv1_1;
    end else begin
        ReadEnablePort_1 = ap_const_lv1_1;
    end
end

/// ReadEnablePort_1_ap_vld assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_275_p2)
begin
    if ((((ap_ST_st17_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_275_p2)) | (ap_ST_st18_fsm_17 == ap_CS_fsm))) begin
        ReadEnablePort_1_ap_vld = ap_const_logic_1;
    end else begin
        ReadEnablePort_1_ap_vld = ap_const_logic_0;
    end
end

/// WriteDataPort_0 assign process. ///
always @ (ap_CS_fsm or p_Result_2_fu_1846_p5)
begin
    if ((ap_ST_st60_fsm_59 == ap_CS_fsm)) begin
        WriteDataPort_0 = ap_const_lv32_0;
    end else if ((ap_ST_st59_fsm_58 == ap_CS_fsm)) begin
        WriteDataPort_0 = p_Result_2_fu_1846_p5;
    end else begin
        WriteDataPort_0 = p_Result_2_fu_1846_p5;
    end
end

/// WriteDataPort_0_ap_vld assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st59_fsm_58 == ap_CS_fsm) | (ap_ST_st60_fsm_59 == ap_CS_fsm))) begin
        WriteDataPort_0_ap_vld = ap_const_logic_1;
    end else begin
        WriteDataPort_0_ap_vld = ap_const_logic_0;
    end
end

/// WriteEnablePort_0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st60_fsm_59 == ap_CS_fsm)) begin
        WriteEnablePort_0 = ap_const_lv1_0;
    end else if ((ap_ST_st59_fsm_58 == ap_CS_fsm)) begin
        WriteEnablePort_0 = ap_const_lv1_1;
    end else begin
        WriteEnablePort_0 = ap_const_lv1_1;
    end
end

/// WriteEnablePort_0_ap_vld assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st59_fsm_58 == ap_CS_fsm) | (ap_ST_st60_fsm_59 == ap_CS_fsm))) begin
        WriteEnablePort_0_ap_vld = ap_const_logic_1;
    end else begin
        WriteEnablePort_0_ap_vld = ap_const_logic_0;
    end
end

/// Y_address0 assign process. ///
always @ (ap_CS_fsm or tmp_49_cast_reg_2012 or exitcond5_fu_816_p2 or Y_addr_9_reg_2022 or Y_addr_6_reg_2034 or Y_addr_1_reg_2040 or Y_addr_4_reg_2073 or Y_addr_reg_2133 or exitcond4_fu_1310_p2 or p_sum5_cast_fu_853_p1 or p_sum1_cast_fu_908_p1 or p_sum3_cast_fu_963_p1 or tmp_97_cast_fu_1333_p1)
begin
    if ((ap_ST_st35_fsm_34 == ap_CS_fsm)) begin
        Y_address0 = Y_addr_reg_2133;
    end else if ((ap_ST_st34_fsm_33 == ap_CS_fsm)) begin
        Y_address0 = Y_addr_6_reg_2034;
    end else if ((ap_ST_st33_fsm_32 == ap_CS_fsm)) begin
        Y_address0 = Y_addr_1_reg_2040;
    end else if ((ap_ST_st32_fsm_31 == ap_CS_fsm)) begin
        Y_address0 = Y_addr_4_reg_2073;
    end else if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        Y_address0 = tmp_49_cast_reg_2012;
    end else if (((ap_ST_st37_fsm_36 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_1310_p2))) begin
        Y_address0 = tmp_97_cast_fu_1333_p1;
    end else if ((ap_ST_st29_fsm_28 == ap_CS_fsm)) begin
        Y_address0 = Y_addr_9_reg_2022;
    end else if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        Y_address0 = p_sum3_cast_fu_963_p1;
    end else if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        Y_address0 = p_sum1_cast_fu_908_p1;
    end else if (((ap_ST_st21_fsm_20 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_fu_816_p2))) begin
        Y_address0 = p_sum5_cast_fu_853_p1;
    end else begin
        Y_address0 = tmp_49_cast_reg_2012;
    end
end

/// Y_address1 assign process. ///
always @ (ap_CS_fsm or exitcond5_fu_816_p2 or Y_addr_9_reg_2022 or Y_addr_5_reg_2028 or Y_addr_2_reg_2045 or Y_addr_3_reg_2067 or p_sum6_cast_fu_873_p1 or p_sum2_cast_fu_928_p1 or p_sum4_cast_fu_983_p1 or p_sum_cast_fu_1109_p1)
begin
    if ((ap_ST_st35_fsm_34 == ap_CS_fsm)) begin
        Y_address1 = Y_addr_5_reg_2028;
    end else if ((ap_ST_st34_fsm_33 == ap_CS_fsm)) begin
        Y_address1 = Y_addr_2_reg_2045;
    end else if ((ap_ST_st33_fsm_32 == ap_CS_fsm)) begin
        Y_address1 = Y_addr_3_reg_2067;
    end else if ((ap_ST_st32_fsm_31 == ap_CS_fsm)) begin
        Y_address1 = Y_addr_9_reg_2022;
    end else if ((ap_ST_st29_fsm_28 == ap_CS_fsm)) begin
        Y_address1 = p_sum_cast_fu_1109_p1;
    end else if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        Y_address1 = p_sum4_cast_fu_983_p1;
    end else if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        Y_address1 = p_sum2_cast_fu_928_p1;
    end else if (((ap_ST_st21_fsm_20 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_fu_816_p2))) begin
        Y_address1 = p_sum6_cast_fu_873_p1;
    end else begin
        Y_address1 = p_sum_cast_fu_1109_p1;
    end
end

/// Y_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond5_fu_816_p2 or exitcond4_fu_1310_p2)
begin
    if ((((ap_ST_st21_fsm_20 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_fu_816_p2)) | (ap_ST_st24_fsm_23 == ap_CS_fsm) | (ap_ST_st25_fsm_24 == ap_CS_fsm) | (ap_ST_st29_fsm_28 == ap_CS_fsm) | (ap_ST_st32_fsm_31 == ap_CS_fsm) | ((ap_ST_st37_fsm_36 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_1310_p2)) | (ap_ST_st35_fsm_34 == ap_CS_fsm) | (ap_ST_st22_fsm_21 == ap_CS_fsm) | (ap_ST_st33_fsm_32 == ap_CS_fsm) | (ap_ST_st34_fsm_33 == ap_CS_fsm))) begin
        Y_ce0 = ap_const_logic_1;
    end else begin
        Y_ce0 = ap_const_logic_0;
    end
end

/// Y_ce1 assign process. ///
always @ (ap_CS_fsm or exitcond5_fu_816_p2)
begin
    if ((((ap_ST_st21_fsm_20 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_fu_816_p2)) | (ap_ST_st24_fsm_23 == ap_CS_fsm) | (ap_ST_st25_fsm_24 == ap_CS_fsm) | (ap_ST_st29_fsm_28 == ap_CS_fsm) | (ap_ST_st32_fsm_31 == ap_CS_fsm) | (ap_ST_st35_fsm_34 == ap_CS_fsm) | (ap_ST_st33_fsm_32 == ap_CS_fsm) | (ap_ST_st34_fsm_33 == ap_CS_fsm))) begin
        Y_ce1 = ap_const_logic_1;
    end else begin
        Y_ce1 = ap_const_logic_0;
    end
end

/// Y_d0 assign process. ///
always @ (ap_CS_fsm or tmp_51_cast_fu_888_p1 or tmp_41_fu_1229_p2 or tmp_43_fu_1244_p2 or tmp_45_fu_1259_p2 or tmp_47_fu_1274_p2)
begin
    if ((ap_ST_st35_fsm_34 == ap_CS_fsm)) begin
        Y_d0 = tmp_47_fu_1274_p2;
    end else if ((ap_ST_st34_fsm_33 == ap_CS_fsm)) begin
        Y_d0 = tmp_45_fu_1259_p2;
    end else if ((ap_ST_st33_fsm_32 == ap_CS_fsm)) begin
        Y_d0 = tmp_43_fu_1244_p2;
    end else if ((ap_ST_st32_fsm_31 == ap_CS_fsm)) begin
        Y_d0 = tmp_41_fu_1229_p2;
    end else if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        Y_d0 = tmp_51_cast_fu_888_p1;
    end else begin
        Y_d0 = tmp_47_fu_1274_p2;
    end
end

/// Y_d1 assign process. ///
always @ (ap_CS_fsm or tmp_42_fu_1235_p2 or tmp_44_fu_1250_p2 or tmp_46_fu_1265_p2 or tmp_48_fu_1280_p2)
begin
    if ((ap_ST_st35_fsm_34 == ap_CS_fsm)) begin
        Y_d1 = tmp_48_fu_1280_p2;
    end else if ((ap_ST_st34_fsm_33 == ap_CS_fsm)) begin
        Y_d1 = tmp_46_fu_1265_p2;
    end else if ((ap_ST_st33_fsm_32 == ap_CS_fsm)) begin
        Y_d1 = tmp_44_fu_1250_p2;
    end else if ((ap_ST_st32_fsm_31 == ap_CS_fsm)) begin
        Y_d1 = tmp_42_fu_1235_p2;
    end else begin
        Y_d1 = tmp_48_fu_1280_p2;
    end
end

/// Y_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st32_fsm_31 == ap_CS_fsm) | (ap_ST_st35_fsm_34 == ap_CS_fsm) | (ap_ST_st22_fsm_21 == ap_CS_fsm) | (ap_ST_st33_fsm_32 == ap_CS_fsm) | (ap_ST_st34_fsm_33 == ap_CS_fsm))) begin
        Y_we0 = ap_const_logic_1;
    end else begin
        Y_we0 = ap_const_logic_0;
    end
end

/// Y_we1 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st32_fsm_31 == ap_CS_fsm) | (ap_ST_st35_fsm_34 == ap_CS_fsm) | (ap_ST_st33_fsm_32 == ap_CS_fsm) | (ap_ST_st34_fsm_33 == ap_CS_fsm))) begin
        Y_we1 = ap_const_logic_1;
    end else begin
        Y_we1 = ap_const_logic_0;
    end
end

/// Yc_address0 assign process. ///
always @ (ap_CS_fsm or Yc_addr_9_reg_1872 or Yc_addr_reg_1878 or Yc_addr_1_reg_1884 or Yc_addr_3_reg_1894 or Yc_addr_4_reg_1900 or Yc_addr_5_reg_1906 or Yc_addr_6_reg_1912 or row_1_cast_reg_2253 or exitcond4_fu_1310_p2 or exitcond7_fu_1641_p2 or row_2_cast1_fu_1632_p1)
begin
    if ((ap_ST_st51_fsm_50 == ap_CS_fsm)) begin
        Yc_address0 = Yc_addr_reg_1878;
    end else if ((ap_ST_st50_fsm_49 == ap_CS_fsm)) begin
        Yc_address0 = Yc_addr_6_reg_1912;
    end else if ((ap_ST_st48_fsm_47 == ap_CS_fsm)) begin
        Yc_address0 = Yc_addr_4_reg_1900;
    end else if ((ap_ST_st38_fsm_37 == ap_CS_fsm)) begin
        Yc_address0 = row_1_cast_reg_2253;
    end else if (((ap_ST_st52_fsm_51 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_1641_p2))) begin
        Yc_address0 = row_2_cast1_fu_1632_p1;
    end else if ((ap_ST_st45_fsm_44 == ap_CS_fsm)) begin
        Yc_address0 = Yc_addr_9_reg_1872;
    end else if ((ap_ST_st41_fsm_40 == ap_CS_fsm)) begin
        Yc_address0 = Yc_addr_3_reg_1894;
    end else if (((ap_ST_st40_fsm_39 == ap_CS_fsm) | (ap_ST_st49_fsm_48 == ap_CS_fsm))) begin
        Yc_address0 = Yc_addr_1_reg_1884;
    end else if (((ap_ST_st37_fsm_36 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_1310_p2))) begin
        Yc_address0 = Yc_addr_5_reg_1906;
    end else begin
        Yc_address0 = row_1_cast_reg_2253;
    end
end

/// Yc_address1 assign process. ///
always @ (ap_CS_fsm or Yc_addr_9_reg_1872 or Yc_addr_reg_1878 or Yc_addr_2_reg_1889 or Yc_addr_3_reg_1894 or Yc_addr_4_reg_1900 or Yc_addr_5_reg_1906 or Yc_addr_6_reg_1912 or exitcond4_fu_1310_p2)
begin
    if ((ap_ST_st51_fsm_50 == ap_CS_fsm)) begin
        Yc_address1 = Yc_addr_5_reg_1906;
    end else if ((ap_ST_st49_fsm_48 == ap_CS_fsm)) begin
        Yc_address1 = Yc_addr_3_reg_1894;
    end else if ((ap_ST_st48_fsm_47 == ap_CS_fsm)) begin
        Yc_address1 = Yc_addr_9_reg_1872;
    end else if ((ap_ST_st45_fsm_44 == ap_CS_fsm)) begin
        Yc_address1 = Yc_addr_reg_1878;
    end else if ((ap_ST_st41_fsm_40 == ap_CS_fsm)) begin
        Yc_address1 = Yc_addr_4_reg_1900;
    end else if (((ap_ST_st40_fsm_39 == ap_CS_fsm) | (ap_ST_st50_fsm_49 == ap_CS_fsm))) begin
        Yc_address1 = Yc_addr_2_reg_1889;
    end else if (((ap_ST_st37_fsm_36 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_1310_p2))) begin
        Yc_address1 = Yc_addr_6_reg_1912;
    end else begin
        Yc_address1 = Yc_addr_6_reg_1912;
    end
end

/// Yc_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond4_fu_1310_p2 or exitcond7_fu_1641_p2)
begin
    if (((ap_ST_st41_fsm_40 == ap_CS_fsm) | (ap_ST_st45_fsm_44 == ap_CS_fsm) | (ap_ST_st48_fsm_47 == ap_CS_fsm) | ((ap_ST_st52_fsm_51 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_1641_p2)) | (ap_ST_st38_fsm_37 == ap_CS_fsm) | (ap_ST_st51_fsm_50 == ap_CS_fsm) | ((ap_ST_st37_fsm_36 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_1310_p2)) | (ap_ST_st40_fsm_39 == ap_CS_fsm) | (ap_ST_st49_fsm_48 == ap_CS_fsm) | (ap_ST_st50_fsm_49 == ap_CS_fsm))) begin
        Yc_ce0 = ap_const_logic_1;
    end else begin
        Yc_ce0 = ap_const_logic_0;
    end
end

/// Yc_ce1 assign process. ///
always @ (ap_CS_fsm or exitcond4_fu_1310_p2)
begin
    if (((ap_ST_st41_fsm_40 == ap_CS_fsm) | (ap_ST_st45_fsm_44 == ap_CS_fsm) | (ap_ST_st48_fsm_47 == ap_CS_fsm) | (ap_ST_st51_fsm_50 == ap_CS_fsm) | ((ap_ST_st37_fsm_36 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_1310_p2)) | (ap_ST_st40_fsm_39 == ap_CS_fsm) | (ap_ST_st49_fsm_48 == ap_CS_fsm) | (ap_ST_st50_fsm_49 == ap_CS_fsm))) begin
        Yc_ce1 = ap_const_logic_1;
    end else begin
        Yc_ce1 = ap_const_logic_0;
    end
end

/// Yc_d0 assign process. ///
always @ (Y_q0 or ap_CS_fsm or tmp_63_fu_1575_p2 or tmp_65_fu_1590_p2 or tmp_67_fu_1605_p2 or tmp_69_fu_1620_p2)
begin
    if ((ap_ST_st51_fsm_50 == ap_CS_fsm)) begin
        Yc_d0 = tmp_69_fu_1620_p2;
    end else if ((ap_ST_st50_fsm_49 == ap_CS_fsm)) begin
        Yc_d0 = tmp_67_fu_1605_p2;
    end else if ((ap_ST_st49_fsm_48 == ap_CS_fsm)) begin
        Yc_d0 = tmp_65_fu_1590_p2;
    end else if ((ap_ST_st48_fsm_47 == ap_CS_fsm)) begin
        Yc_d0 = tmp_63_fu_1575_p2;
    end else if ((ap_ST_st38_fsm_37 == ap_CS_fsm)) begin
        Yc_d0 = Y_q0;
    end else begin
        Yc_d0 = tmp_69_fu_1620_p2;
    end
end

/// Yc_d1 assign process. ///
always @ (ap_CS_fsm or tmp_64_fu_1581_p2 or tmp_66_fu_1596_p2 or tmp_68_fu_1611_p2 or tmp_70_fu_1626_p2)
begin
    if ((ap_ST_st51_fsm_50 == ap_CS_fsm)) begin
        Yc_d1 = tmp_70_fu_1626_p2;
    end else if ((ap_ST_st50_fsm_49 == ap_CS_fsm)) begin
        Yc_d1 = tmp_68_fu_1611_p2;
    end else if ((ap_ST_st49_fsm_48 == ap_CS_fsm)) begin
        Yc_d1 = tmp_66_fu_1596_p2;
    end else if ((ap_ST_st48_fsm_47 == ap_CS_fsm)) begin
        Yc_d1 = tmp_64_fu_1581_p2;
    end else begin
        Yc_d1 = tmp_70_fu_1626_p2;
    end
end

/// Yc_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st48_fsm_47 == ap_CS_fsm) | (ap_ST_st38_fsm_37 == ap_CS_fsm) | (ap_ST_st51_fsm_50 == ap_CS_fsm) | (ap_ST_st49_fsm_48 == ap_CS_fsm) | (ap_ST_st50_fsm_49 == ap_CS_fsm))) begin
        Yc_we0 = ap_const_logic_1;
    end else begin
        Yc_we0 = ap_const_logic_0;
    end
end

/// Yc_we1 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st48_fsm_47 == ap_CS_fsm) | (ap_ST_st51_fsm_50 == ap_CS_fsm) | (ap_ST_st49_fsm_48 == ap_CS_fsm) | (ap_ST_st50_fsm_49 == ap_CS_fsm))) begin
        Yc_we1 = ap_const_logic_1;
    end else begin
        Yc_we1 = ap_const_logic_0;
    end
end

/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or tmp_4_reg_1923 or indvar1_phi_fu_518_p4 or tmp_8_fu_696_p2 or indvar_phi_fu_529_p4 or exitcond2_fu_790_p2 or exitcond5_fu_816_p2 or exitcond4_fu_1310_p2 or exitcond7_fu_1641_p2 or exitcond6_fu_1822_p2 or exitcond_fu_716_p2 or exitcond1_fu_758_p2 or exitcond3_fu_1290_p2 or grp_wireread_fu_275_p2 or grp_wireread_fu_262_p2 or grp_wireread_fu_288_p2)
begin
    if ((ap_ST_st60_fsm_59 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st61_fsm_60;
    end else if ((ap_ST_st59_fsm_58 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st60_fsm_59;
    end else if ((ap_ST_st58_fsm_57 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st59_fsm_58;
    end else if (((ap_ST_st57_fsm_56 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_288_p2))) begin
        ap_NS_fsm = ap_ST_st58_fsm_57;
    end else if ((((ap_ST_st56_fsm_55 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_1822_p2)) | ((ap_ST_st57_fsm_56 == ap_CS_fsm) & ~(ap_const_lv1_0 == grp_wireread_fu_288_p2)))) begin
        ap_NS_fsm = ap_ST_st57_fsm_56;
    end else if ((ap_ST_st54_fsm_53 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st55_fsm_54;
    end else if ((ap_ST_st53_fsm_52 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st54_fsm_53;
    end else if (((ap_ST_st52_fsm_51 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_1641_p2))) begin
        ap_NS_fsm = ap_ST_st53_fsm_52;
    end else if (((ap_ST_st51_fsm_50 == ap_CS_fsm) | (ap_ST_st55_fsm_54 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st52_fsm_51;
    end else if ((ap_ST_st50_fsm_49 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st51_fsm_50;
    end else if ((ap_ST_st49_fsm_48 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st50_fsm_49;
    end else if ((ap_ST_st48_fsm_47 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st49_fsm_48;
    end else if ((ap_ST_st47_fsm_46 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st48_fsm_47;
    end else if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st47_fsm_46;
    end else if ((ap_ST_st45_fsm_44 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st46_fsm_45;
    end else if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st45_fsm_44;
    end else if ((ap_ST_st43_fsm_42 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st44_fsm_43;
    end else if ((ap_ST_st42_fsm_41 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st43_fsm_42;
    end else if ((ap_ST_st41_fsm_40 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st42_fsm_41;
    end else if ((ap_ST_st40_fsm_39 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st41_fsm_40;
    end else if ((ap_ST_st39_fsm_38 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st40_fsm_39;
    end else if (((ap_ST_st37_fsm_36 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_1310_p2))) begin
        ap_NS_fsm = ap_ST_st39_fsm_38;
    end else if (((ap_ST_st37_fsm_36 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_1310_p2))) begin
        ap_NS_fsm = ap_ST_st38_fsm_37;
    end else if (((ap_ST_st61_fsm_60 == ap_CS_fsm) | ((ap_ST_st36_fsm_35 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond3_fu_1290_p2)))) begin
        ap_NS_fsm = ap_ST_st56_fsm_55;
    end else if (((ap_ST_st38_fsm_37 == ap_CS_fsm) | ((ap_ST_st36_fsm_35 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_1290_p2)))) begin
        ap_NS_fsm = ap_ST_st37_fsm_36;
    end else if ((ap_ST_st34_fsm_33 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st35_fsm_34;
    end else if ((ap_ST_st33_fsm_32 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st34_fsm_33;
    end else if ((ap_ST_st32_fsm_31 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st33_fsm_32;
    end else if ((ap_ST_st31_fsm_30 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st32_fsm_31;
    end else if ((ap_ST_st30_fsm_29 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st31_fsm_30;
    end else if ((ap_ST_st29_fsm_28 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st30_fsm_29;
    end else if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st29_fsm_28;
    end else if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st28_fsm_27;
    end else if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st27_fsm_26;
    end else if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st26_fsm_25;
    end else if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st25_fsm_24;
    end else if ((ap_ST_st23_fsm_22 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st24_fsm_23;
    end else if (((ap_ST_st21_fsm_20 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_fu_816_p2))) begin
        ap_NS_fsm = ap_ST_st23_fsm_22;
    end else if (((ap_ST_st21_fsm_20 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_fu_816_p2))) begin
        ap_NS_fsm = ap_ST_st22_fsm_21;
    end else if ((((ap_ST_st20_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_790_p2)) | (ap_ST_st22_fsm_21 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st21_fsm_20;
    end else if ((((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_790_p2)) | ((ap_ST_st52_fsm_51 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_1641_p2)))) begin
        ap_NS_fsm = ap_ST_st36_fsm_35;
    end else if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st19_fsm_18;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_275_p2))) begin
        ap_NS_fsm = ap_ST_st18_fsm_17;
    end else if (((ap_ST_st35_fsm_34 == ap_CS_fsm) | ((ap_ST_st16_fsm_15 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_758_p2)))) begin
        ap_NS_fsm = ap_ST_st20_fsm_19;
    end else if ((((ap_ST_st16_fsm_15 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_758_p2)) | ((ap_ST_st17_fsm_16 == ap_CS_fsm) & ~(ap_const_lv1_0 == grp_wireread_fu_275_p2)))) begin
        ap_NS_fsm = ap_ST_st17_fsm_16;
    end else if ((((ap_ST_st15_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_716_p2)) | (ap_ST_st19_fsm_18 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st16_fsm_15;
    end else if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st14_fsm_13;
    end else if (((ap_ST_st12_fsm_11 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_262_p2))) begin
        ap_NS_fsm = ap_ST_st13_fsm_12;
    end else if ((((ap_ST_st11_fsm_10 == ap_CS_fsm) & (((tmp_4_reg_1923 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_8_fu_696_p2)) | (~(ap_const_lv1_0 == tmp_8_fu_696_p2) & ~(ap_const_lv1_0 == indvar_phi_fu_529_p4)))) | ((ap_ST_st56_fsm_55 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond6_fu_1822_p2)))) begin
        ap_NS_fsm = ap_ST_st15_fsm_14;
    end else if ((((ap_ST_st11_fsm_10 == ap_CS_fsm) & ~(tmp_4_reg_1923 == ap_const_lv1_0) & (ap_const_lv1_0 == indvar_phi_fu_529_p4)) | ((ap_ST_st12_fsm_11 == ap_CS_fsm) & ~(ap_const_lv1_0 == grp_wireread_fu_262_p2)))) begin
        ap_NS_fsm = ap_ST_st12_fsm_11;
    end else if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st10_fsm_9;
    end else if (((ap_const_lv1_0 == grp_wireread_fu_262_p2) & (ap_ST_st8_fsm_7 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st9_fsm_8;
    end else if ((((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(indvar1_phi_fu_518_p4 == ap_const_lv1_0)) | (ap_ST_st14_fsm_13 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st11_fsm_10;
    end else if ((((ap_ST_st7_fsm_6 == ap_CS_fsm) & (indvar1_phi_fu_518_p4 == ap_const_lv1_0)) | ((ap_ST_st8_fsm_7 == ap_CS_fsm) & ~(ap_const_lv1_0 == grp_wireread_fu_262_p2)))) begin
        ap_NS_fsm = ap_ST_st8_fsm_7;
    end else if (((ap_ST_st10_fsm_9 == ap_CS_fsm) | (ap_ST_st6_fsm_5 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st7_fsm_6;
    end else if (((ap_ST_st5_fsm_4 == ap_CS_fsm) | ((ap_ST_st11_fsm_10 == ap_CS_fsm) & (((tmp_4_reg_1923 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_8_fu_696_p2)) | ((ap_const_lv1_0 == tmp_8_fu_696_p2) & ~(ap_const_lv1_0 == indvar_phi_fu_529_p4)))) | ((ap_ST_st15_fsm_14 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_716_p2)))) begin
        ap_NS_fsm = ap_ST_st6_fsm_5;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st5_fsm_4;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st4_fsm_3;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st3_fsm_2;
    end else if ((ap_ST_st1_fsm_0 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st2_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// in_address0 assign process. ///
always @ (ap_CS_fsm or in_addr_1_reg_1959 or tmp_49_cast_fu_833_p1 or exitcond5_fu_816_p2 or grp_wireread_fu_275_p2)
begin
    if (((ap_ST_st17_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_275_p2))) begin
        in_address0 = in_addr_1_reg_1959;
    end else if (((ap_ST_st21_fsm_20 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_fu_816_p2))) begin
        in_address0 = tmp_49_cast_fu_833_p1;
    end else begin
        in_address0 = tmp_49_cast_fu_833_p1;
    end
end

/// in_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond5_fu_816_p2 or grp_wireread_fu_275_p2)
begin
    if ((((ap_ST_st21_fsm_20 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_fu_816_p2)) | ((ap_ST_st17_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_275_p2)))) begin
        in_ce0 = ap_const_logic_1;
    end else begin
        in_ce0 = ap_const_logic_0;
    end
end

/// in_ce1 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_275_p2)
begin
    if (((ap_ST_st17_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_275_p2))) begin
        in_ce1 = ap_const_logic_1;
    end else begin
        in_ce1 = ap_const_logic_0;
    end
end

/// in_we0 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_275_p2)
begin
    if (((ap_ST_st17_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_275_p2))) begin
        in_we0 = ap_const_logic_1;
    end else begin
        in_we0 = ap_const_logic_0;
    end
end

/// in_we1 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_275_p2)
begin
    if (((ap_ST_st17_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_275_p2))) begin
        in_we1 = ap_const_logic_1;
    end else begin
        in_we1 = ap_const_logic_0;
    end
end
assign Idct_d0 = ((tmp_92_reg_2460)? phitmp_reg_2465: ap_const_lv8_0);
assign Yc_addr_1_gep_fu_309_p3 = ap_const_lv32_6;
assign Yc_addr_2_gep_fu_316_p3 = ap_const_lv32_2;
assign Yc_addr_3_gep_fu_323_p3 = ap_const_lv32_1;
assign Yc_addr_4_gep_fu_330_p3 = ap_const_lv32_7;
assign Yc_addr_5_gep_fu_337_p3 = ap_const_lv32_3;
assign Yc_addr_6_gep_fu_344_p3 = ap_const_lv32_5;
assign Yc_addr_9_gep_fu_295_p3 = ap_const_lv32_0;
assign Yc_addr_gep_fu_302_p3 = ap_const_lv32_4;
assign block_1_fu_721_p2 = (block_reg_536 + ap_const_lv32_1);
assign column_1_cast_fu_812_p1 = $unsigned(column_1_reg_569);
assign column_2_fu_822_p2 = (column_1_reg_569 + ap_const_lv4_1);
assign column_3_fu_1296_p2 = (column_reg_580 + ap_const_lv4_1);
assign column_cast_fu_1286_p1 = $unsigned(column_reg_580);
assign exitcond1_fu_758_p2 = (i_reg_547 == ap_const_lv6_20? 1'b1: 1'b0);
assign exitcond2_fu_790_p2 = (row_reg_558 == ap_const_lv4_8? 1'b1: 1'b0);
assign exitcond3_fu_1290_p2 = (column_reg_580 == ap_const_lv4_8? 1'b1: 1'b0);
assign exitcond4_fu_1310_p2 = (row_1_reg_591 == ap_const_lv4_8? 1'b1: 1'b0);
assign exitcond5_fu_816_p2 = (column_1_reg_569 == ap_const_lv4_8? 1'b1: 1'b0);
assign exitcond6_fu_1822_p2 = (i_2_reg_613 == ap_const_lv5_10? 1'b1: 1'b0);
assign exitcond7_fu_1641_p2 = (row_2_reg_602 == ap_const_lv4_8? 1'b1: 1'b0);
assign exitcond_fu_716_p2 = (block_reg_536 == tmp1_reg_1938? 1'b1: 1'b0);
assign grp_fu_1003_ce = ap_const_logic_1;
assign grp_fu_1003_p0 = Y_load_7_reg_2055;
assign grp_fu_1003_p1 = ap_const_lv32_22A3;
assign grp_fu_1058_ce = ap_const_logic_1;
assign grp_fu_1058_p0 = x_assign_1_reg_2095;
assign grp_fu_1058_p1 = ap_const_lv32_3537;
assign grp_fu_1063_ce = ap_const_logic_1;
assign grp_fu_1063_p0 = y_assign_1_reg_2107;
assign grp_fu_1063_p1 = ap_const_lv32_238E;
assign grp_fu_1068_ce = ap_const_logic_1;
assign grp_fu_1068_p0 = x_assign_1_reg_2095;
assign grp_fu_1068_p1 = ap_const_lv32_238E;
assign grp_fu_1073_ce = ap_const_logic_1;
assign grp_fu_1073_p0 = y_assign_1_reg_2107;
assign grp_fu_1073_p1 = ap_const_lv32_3537;
assign grp_fu_1078_ce = ap_const_logic_1;
assign grp_fu_1078_p0 = x_assign_2_reg_2101;
assign grp_fu_1078_p1 = ap_const_lv32_3EC5;
assign grp_fu_1083_ce = ap_const_logic_1;
assign grp_fu_1083_p0 = y_assign_2_reg_2089;
assign grp_fu_1083_p1 = ap_const_lv32_C7C;
assign grp_fu_1088_ce = ap_const_logic_1;
assign grp_fu_1088_p0 = x_assign_2_reg_2101;
assign grp_fu_1088_p1 = ap_const_lv32_C7C;
assign grp_fu_1093_ce = ap_const_logic_1;
assign grp_fu_1093_p0 = y_assign_2_reg_2089;
assign grp_fu_1093_p1 = ap_const_lv32_3EC5;
assign grp_fu_1338_ce = ap_const_logic_1;
assign grp_fu_1338_p0 = reg_636;
assign grp_fu_1338_p1 = ap_const_lv32_5A82;
assign grp_fu_1344_ce = ap_const_logic_1;
assign grp_fu_1344_p0 = reg_640;
assign grp_fu_1344_p1 = ap_const_lv32_5A82;
assign grp_fu_1350_ce = ap_const_logic_1;
assign grp_fu_1350_p0 = Yc_load_8_reg_2277;
assign grp_fu_1350_p1 = ap_const_lv32_22A3;
assign grp_fu_1355_ce = ap_const_logic_1;
assign grp_fu_1355_p0 = Yc_load_2_reg_2271;
assign grp_fu_1355_p1 = ap_const_lv32_539F;
assign grp_fu_1360_ce = ap_const_logic_1;
assign grp_fu_1360_p0 = Yc_load_8_reg_2277;
assign grp_fu_1360_p1 = ap_const_lv32_539F;
assign grp_fu_1365_ce = ap_const_logic_1;
assign grp_fu_1365_p0 = Yc_load_2_reg_2271;
assign grp_fu_1365_p1 = ap_const_lv32_22A3;
assign grp_fu_1420_ce = ap_const_logic_1;
assign grp_fu_1420_p0 = x_assign_4_reg_2299;
assign grp_fu_1420_p1 = ap_const_lv32_3537;
assign grp_fu_1425_ce = ap_const_logic_1;
assign grp_fu_1425_p0 = y_assign_4_reg_2311;
assign grp_fu_1425_p1 = ap_const_lv32_238E;
assign grp_fu_1430_ce = ap_const_logic_1;
assign grp_fu_1430_p0 = x_assign_4_reg_2299;
assign grp_fu_1430_p1 = ap_const_lv32_238E;
assign grp_fu_1435_ce = ap_const_logic_1;
assign grp_fu_1435_p0 = y_assign_4_reg_2311;
assign grp_fu_1435_p1 = ap_const_lv32_3537;
assign grp_fu_1440_ce = ap_const_logic_1;
assign grp_fu_1440_p0 = x_assign_5_reg_2305;
assign grp_fu_1440_p1 = ap_const_lv32_3EC5;
assign grp_fu_1445_ce = ap_const_logic_1;
assign grp_fu_1445_p0 = y_assign_5_reg_2293;
assign grp_fu_1445_p1 = ap_const_lv32_C7C;
assign grp_fu_1450_ce = ap_const_logic_1;
assign grp_fu_1450_p0 = x_assign_5_reg_2305;
assign grp_fu_1450_p1 = ap_const_lv32_C7C;
assign grp_fu_1455_ce = ap_const_logic_1;
assign grp_fu_1455_p0 = y_assign_5_reg_2293;
assign grp_fu_1455_p1 = ap_const_lv32_3EC5;
assign grp_fu_644_p0 = reg_628;
assign grp_fu_644_p1 = reg_632;
assign grp_fu_644_p2 = (grp_fu_644_p0 - grp_fu_644_p1);
assign grp_fu_650_p0 = reg_632;
assign grp_fu_650_p1 = reg_628;
assign grp_fu_650_p2 = (grp_fu_650_p0 + grp_fu_650_p1);
assign grp_fu_656_p0 = reg_636;
assign grp_fu_656_p1 = reg_640;
assign grp_fu_656_p2 = (grp_fu_656_p0 - grp_fu_656_p1);
assign grp_fu_662_p0 = reg_640;
assign grp_fu_662_p1 = reg_636;
assign grp_fu_662_p2 = (grp_fu_662_p0 + grp_fu_662_p1);
assign grp_fu_933_ce = ap_const_logic_1;
assign grp_fu_933_p0 = reg_628;
assign grp_fu_933_p1 = ap_const_lv32_5A82;
assign grp_fu_939_ce = ap_const_logic_1;
assign grp_fu_939_p0 = reg_632;
assign grp_fu_939_p1 = ap_const_lv32_5A82;
assign grp_fu_988_ce = ap_const_logic_1;
assign grp_fu_988_p0 = Y_load_8_reg_2061;
assign grp_fu_988_p1 = ap_const_lv32_22A3;
assign grp_fu_993_ce = ap_const_logic_1;
assign grp_fu_993_p0 = Y_load_7_reg_2055;
assign grp_fu_993_p1 = ap_const_lv32_539F;
assign grp_fu_998_ce = ap_const_logic_1;
assign grp_fu_998_p0 = Y_load_8_reg_2061;
assign grp_fu_998_p1 = ap_const_lv32_539F;
assign grp_wireread_fu_262_p2 = ReadEmptyPort_0;
assign grp_wireread_fu_275_p2 = ReadEmptyPort_1;
assign grp_wireread_fu_288_p2 = WriteFullPort_0;
assign i_1_fu_764_p2 = (i_reg_547 + ap_const_lv6_1);
assign i_3_fu_1828_p2 = (i_2_reg_613 + ap_const_lv5_1);
assign i_4_cast_fu_727_p1 = $unsigned(i_reg_547);
assign i_6_cast_fu_1756_p1 = $unsigned(i_2_reg_613);
assign icmp_fu_1727_p2 = ($signed(tmp_93_fu_1717_p4) < $signed(19'b0000000000000000001)? 1'b1: 1'b0);
assign in_address1 = ptData3_0_sum238241_i_cast_reg_1954;
assign in_d0 = ReadDataPort_1[15:0];
assign in_d1 = {{ReadDataPort_1[ap_const_lv32_1F : ap_const_lv32_10]}};
assign indvar1_phi_fu_518_p4 = indvar1_reg_514;
assign indvar_next1_fu_673_p2 = (indvar1_reg_514 ^ ap_const_lv1_1);
assign indvar_next_fu_690_p2 = (indvar_reg_525 ^ ap_const_lv1_1);
assign indvar_phi_fu_529_p4 = indvar_reg_525;
assign p_Result_2_fu_1846_p5 = {{tmp_87_fu_1837_p4}, {p_Result_s_fu_1834_p1[32'd7 : 32'd0]}};
assign p_Result_s_fu_1834_p1 = $unsigned(Idct_load_reg_2501);
assign p_sum1_cast_fu_908_p1 = $unsigned(p_sum1_fu_896_p5);
assign p_sum1_fu_896_p5 = {{tmp_74_fu_893_p1}, {ap_const_lv6_6[32'd2 : 32'd0]}};
assign p_sum2_cast_fu_928_p1 = $unsigned(p_sum2_fu_916_p5);
assign p_sum2_fu_916_p5 = {{tmp_75_fu_913_p1}, {ap_const_lv6_2[32'd2 : 32'd0]}};
assign p_sum3_cast_fu_963_p1 = $unsigned(p_sum3_fu_951_p5);
assign p_sum3_fu_951_p5 = {{tmp_78_fu_948_p1}, {ap_const_lv6_1[32'd2 : 32'd0]}};
assign p_sum4_cast_fu_983_p1 = $unsigned(p_sum4_fu_971_p5);
assign p_sum4_fu_971_p5 = {{tmp_79_fu_968_p1}, {ap_const_lv6_7[32'd2 : 32'd0]}};
assign p_sum5_cast_fu_853_p1 = $unsigned(p_sum5_fu_841_p5);
assign p_sum5_fu_841_p5 = {{tmp_80_fu_838_p1}, {ap_const_lv6_3[32'd2 : 32'd0]}};
assign p_sum6_cast_fu_873_p1 = $unsigned(p_sum6_fu_861_p5);
assign p_sum6_fu_861_p5 = {{tmp_82_fu_858_p1}, {ap_const_lv6_5[32'd2 : 32'd0]}};
assign p_sum_cast_fu_1109_p1 = $unsigned(p_sum_fu_1098_p5);
assign p_sum_fu_1098_p5 = {{tmp_73_reg_2050}, {ap_const_lv6_4[32'd2 : 32'd0]}};
assign phitmp_fu_1737_p3 = ((icmp_fu_1727_p2)? tmp_94_fu_1733_p1: ap_const_lv8_FF);
assign ptData3_0_rec_i_cast_fu_737_p1 = $unsigned(ptData3_0_rec_i_fu_731_p2);
assign ptData3_0_rec_i_fu_731_p2 = i_4_cast_fu_727_p1 << ap_const_lv7_1;
assign ptData3_0_sum238241_i_cast_fu_754_p1 = $unsigned(ptData3_0_sum238241_i_fu_742_p5);
assign ptData3_0_sum238241_i_fu_742_p5 = {{i_reg_547}, {ap_const_lv7_1[32'd0 : 32'd0]}};
assign r_fu_1705_p0 = $signed(tmp_91_reg_2455);
assign r_fu_1705_p2 = (r_fu_1705_p0 + ap_const_lv27_80);
assign row_1_cast1_fu_1302_p1 = $unsigned(row_1_reg_591);
assign row_1_cast_fu_1306_p1 = $unsigned(row_1_reg_591);
assign row_2_cast1_fu_1632_p1 = $unsigned(row_2_reg_602);
assign row_2_cast_fu_1637_p1 = $unsigned(row_2_reg_602);
assign row_3_fu_796_p2 = (row_reg_558 + ap_const_lv4_1);
assign row_4_fu_1316_p2 = (row_1_reg_591 + ap_const_lv4_1);
assign row_5_fu_1647_p2 = (row_2_reg_602 + ap_const_lv4_1);
assign row_cast_fu_786_p1 = $unsigned(row_reg_558);
assign tmp1_fu_705_p2 = NBLOCKS_fu_206 << ap_const_lv32_1;
assign tmp332338_i_cast_fu_1783_p1 = $unsigned(tmp332338_i_fu_1771_p5);
assign tmp332338_i_fu_1771_p5 = {{i_2_reg_613}, {ap_const_lv7_3[32'd1 : 32'd0]}};
assign tmp333339_i_cast_fu_1800_p1 = $unsigned(tmp333339_i_fu_1788_p5);
assign tmp333339_i_fu_1788_p5 = {{i_2_reg_613}, {ap_const_lv7_2[32'd1 : 32'd0]}};
assign tmp335340_i_cast_fu_1817_p1 = $unsigned(tmp335340_i_fu_1805_p5);
assign tmp335340_i_fu_1805_p5 = {{i_2_reg_613}, {ap_const_lv7_1[32'd1 : 32'd0]}};
assign tmp_107_cast_fu_1752_p1 = $unsigned(tmp_96_reg_2450);
assign tmp_12_fu_1128_p2 = (tmp_11_reg_2128 + tmp_10_reg_2123);
assign tmp_13_fu_1460_p2 = (tmp_6_reg_2317 - tmp_7_reg_2322);
assign tmp_18_fu_1474_p2 = (tmp_16_reg_2332 + tmp_15_reg_2327);
assign tmp_27_fu_1157_p2 = (tmp_25_reg_2149 - tmp_26_reg_2154);
assign tmp_2_cast_fu_808_p1 = $unsigned(tmp_2_fu_802_p2);
assign tmp_2_fu_802_p2 = row_cast_fu_786_p1 << ap_const_lv6_3;
assign tmp_31_fu_1171_p2 = (tmp_30_reg_2164 + tmp_29_reg_2159);
assign tmp_35_fu_1185_p2 = (tmp_33_reg_2169 - tmp_34_reg_2174);
assign tmp_36_fu_1503_p2 = (tmp_28_reg_2347 - tmp_32_reg_2352);
assign tmp_39_fu_1199_p2 = (tmp_38_reg_2184 + tmp_37_reg_2179);
assign tmp_3_fu_1114_p2 = (tmp_9_reg_2113 - tmp_s_reg_2118);
assign tmp_41_fu_1229_p1 = z3_7_fu_1226_p1;
assign tmp_41_fu_1229_p2 = (z3_0_reg_2201 - tmp_41_fu_1229_p1);
assign tmp_42_fu_1235_p1 = z3_7_fu_1226_p1;
assign tmp_42_fu_1235_p2 = (z3_0_reg_2201 + tmp_42_fu_1235_p1);
assign tmp_43_fu_1244_p1 = z3_6_fu_1241_p1;
assign tmp_43_fu_1244_p2 = (z3_1_reg_2233 - tmp_43_fu_1244_p1);
assign tmp_44_fu_1250_p1 = z3_6_fu_1241_p1;
assign tmp_44_fu_1250_p2 = (z3_1_reg_2233 + tmp_44_fu_1250_p1);
assign tmp_45_fu_1259_p1 = z3_5_fu_1256_p1;
assign tmp_45_fu_1259_p2 = (z3_2_reg_2227 - tmp_45_fu_1259_p1);
assign tmp_46_fu_1265_p1 = z3_5_fu_1256_p1;
assign tmp_46_fu_1265_p2 = (z3_2_reg_2227 + tmp_46_fu_1265_p1);
assign tmp_47_fu_1274_p1 = z3_4_fu_1271_p1;
assign tmp_47_fu_1274_p2 = (z3_3_reg_2195 - tmp_47_fu_1274_p1);
assign tmp_48_fu_1280_p1 = z3_4_fu_1271_p1;
assign tmp_48_fu_1280_p2 = (z3_3_reg_2195 + tmp_48_fu_1280_p1);
assign tmp_49_cast_fu_833_p1 = $unsigned(tmp_49_fu_828_p2);
assign tmp_49_fu_828_p2 = (column_1_cast_fu_812_p1 + tmp_2_reg_1994);
assign tmp_4_fu_679_p2 = (uiCommand_fu_210 == ap_const_lv32_1? 1'b1: 1'b0);
assign tmp_50_cast_fu_878_p1 = $unsigned(in_q0);
assign tmp_51_cast_fu_888_p1 = $signed(tmp_51_fu_882_p2);
assign tmp_51_fu_882_p2 = tmp_50_cast_fu_878_p1 << ap_const_lv19_3;
assign tmp_53_fu_1517_p2 = (tmp_52_reg_2362 + tmp_50_reg_2357);
assign tmp_57_fu_1531_p2 = (tmp_55_reg_2367 - tmp_56_reg_2372);
assign tmp_61_fu_1545_p2 = (tmp_60_reg_2382 + tmp_59_reg_2377);
assign tmp_63_fu_1575_p1 = z3_7_1_fu_1572_p1;
assign tmp_63_fu_1575_p2 = (z3_0_1_reg_2399 - tmp_63_fu_1575_p1);
assign tmp_64_fu_1581_p1 = z3_7_1_fu_1572_p1;
assign tmp_64_fu_1581_p2 = (z3_0_1_reg_2399 + tmp_64_fu_1581_p1);
assign tmp_65_fu_1590_p1 = z3_6_1_fu_1587_p1;
assign tmp_65_fu_1590_p2 = (z3_1_1_reg_2431 - tmp_65_fu_1590_p1);
assign tmp_66_fu_1596_p1 = z3_6_1_fu_1587_p1;
assign tmp_66_fu_1596_p2 = (z3_1_1_reg_2431 + tmp_66_fu_1596_p1);
assign tmp_67_fu_1605_p1 = z3_5_1_fu_1602_p1;
assign tmp_67_fu_1605_p2 = (z3_2_1_reg_2425 - tmp_67_fu_1605_p1);
assign tmp_68_fu_1611_p1 = z3_5_1_fu_1602_p1;
assign tmp_68_fu_1611_p2 = (z3_2_1_reg_2425 + tmp_68_fu_1611_p1);
assign tmp_69_fu_1620_p1 = z3_4_1_fu_1617_p1;
assign tmp_69_fu_1620_p2 = (z3_3_1_reg_2393 - tmp_69_fu_1620_p1);
assign tmp_70_fu_1626_p1 = z3_4_1_fu_1617_p1;
assign tmp_70_fu_1626_p2 = (z3_3_1_reg_2393 + tmp_70_fu_1626_p1);
assign tmp_71_fu_1322_p2 = row_1_cast1_fu_1302_p1 << ap_const_lv6_3;
assign tmp_72_fu_1328_p2 = (tmp_71_fu_1322_p2 + column_cast_reg_2239);
assign tmp_73_fu_945_p1 = row_cast_reg_1975[2:0];
assign tmp_74_fu_893_p1 = row_cast_reg_1975[2:0];
assign tmp_75_fu_913_p1 = row_cast_reg_1975[2:0];
assign tmp_78_fu_948_p1 = row_cast_reg_1975[2:0];
assign tmp_79_fu_968_p1 = row_cast_reg_1975[2:0];
assign tmp_80_fu_838_p1 = row_cast_reg_1975[2:0];
assign tmp_82_fu_858_p1 = row_cast_reg_1975[2:0];
assign tmp_87_fu_1837_p4 = {{{{Idct_q1}, {Idct_q0}}}, {Idct_load_1_reg_2506}};
assign tmp_89_fu_1664_p3 = Yc_q0[ap_const_lv32_1F];
assign tmp_8_fu_696_p2 = (uiCommand_fu_210 == ap_const_lv32_2? 1'b1: 1'b0);
assign tmp_90_fu_1686_p2 = (tmp_cast_fu_1682_p1 + Yc_q0);
assign tmp_92_fu_1711_p2 = ($signed(r_fu_1705_p2) > $signed(27'b000000000000000000000000000)? 1'b1: 1'b0);
assign tmp_93_fu_1717_p4 = {{r_fu_1705_p2[ap_const_lv32_1A : ap_const_lv32_8]}};
assign tmp_94_fu_1733_p1 = r_fu_1705_p2[7:0];
assign tmp_95_fu_1653_p2 = row_2_cast_fu_1637_p1 << ap_const_lv6_3;
assign tmp_96_fu_1659_p2 = (tmp_95_fu_1653_p2 + column_cast_reg_2239);
assign tmp_97_cast_fu_1333_p1 = $unsigned(tmp_72_fu_1328_p2);
assign tmp_cast_fu_1682_p1 = $unsigned(tmp_fu_1676_p2);
assign tmp_fu_1676_p0 = $signed(tmp_89_fu_1664_p3);
assign tmp_fu_1676_p2 = (tmp_fu_1676_p0 ^ ap_const_lv6_20);
assign tmp_i_cast_fu_1766_p1 = $unsigned(tmp_i_fu_1760_p2);
assign tmp_i_fu_1760_p2 = i_6_cast_fu_1756_p1 << ap_const_lv7_2;
assign x_assign_1_fu_1040_p1 = z1_6_fu_1031_p1;
assign x_assign_1_fu_1040_p2 = (grp_fu_644_p2 + x_assign_1_fu_1040_p1);
assign x_assign_2_fu_1046_p1 = z1_5_fu_1028_p1;
assign x_assign_2_fu_1046_p2 = (grp_fu_650_p2 - x_assign_2_fu_1046_p1);
assign x_assign_4_fu_1402_p1 = z1_6_1_fu_1393_p1;
assign x_assign_4_fu_1402_p2 = (grp_fu_656_p2 + x_assign_4_fu_1402_p1);
assign x_assign_5_fu_1408_p1 = z1_5_1_fu_1390_p1;
assign x_assign_5_fu_1408_p2 = (grp_fu_662_p2 - x_assign_5_fu_1408_p1);
assign y_assign_1_fu_1052_p1 = z1_5_fu_1028_p1;
assign y_assign_1_fu_1052_p2 = (grp_fu_650_p2 + y_assign_1_fu_1052_p1);
assign y_assign_2_fu_1034_p1 = z1_6_fu_1031_p1;
assign y_assign_2_fu_1034_p2 = (grp_fu_644_p2 - y_assign_2_fu_1034_p1);
assign y_assign_4_fu_1414_p1 = z1_5_1_fu_1390_p1;
assign y_assign_4_fu_1414_p2 = (grp_fu_662_p2 + y_assign_4_fu_1414_p1);
assign y_assign_5_fu_1396_p1 = z1_6_1_fu_1393_p1;
assign y_assign_5_fu_1396_p2 = (grp_fu_656_p2 - y_assign_5_fu_1396_p1);
assign z1_2_1_fu_1559_p1 = $signed(tmp_14_reg_2337);
assign z1_2_fu_1213_p1 = $signed(tmp_76_reg_2139);
assign z1_3_1_fu_1488_p1 = $signed(tmp_20_reg_2342);
assign z1_3_fu_1142_p1 = $signed(tmp_77_reg_2144);
assign z1_5_1_fu_1390_p1 = $signed(tmp_22_reg_2283);
assign z1_5_fu_1028_p1 = $signed(tmp_81_reg_2079);
assign z1_6_1_fu_1393_p1 = $signed(tmp_24_reg_2288);
assign z1_6_fu_1031_p1 = $signed(tmp_83_reg_2084);
assign z3_0_1_fu_1497_p1 = z1_3_1_fu_1488_p1;
assign z3_0_1_fu_1497_p2 = (grp_fu_662_p2 + z3_0_1_fu_1497_p1);
assign z3_0_fu_1151_p1 = z1_3_fu_1142_p1;
assign z3_0_fu_1151_p2 = (grp_fu_650_p2 + z3_0_fu_1151_p1);
assign z3_1_1_fu_1567_p1 = z1_2_1_fu_1559_p1;
assign z3_1_1_fu_1567_p2 = (z1_1_1_reg_2387 + z3_1_1_fu_1567_p1);
assign z3_1_fu_1221_p1 = z1_2_fu_1213_p1;
assign z3_1_fu_1221_p2 = (z1_1_reg_2189 + z3_1_fu_1221_p1);
assign z3_2_1_fu_1562_p1 = z1_2_1_fu_1559_p1;
assign z3_2_1_fu_1562_p2 = (z1_1_1_reg_2387 - z3_2_1_fu_1562_p1);
assign z3_2_fu_1216_p1 = z1_2_fu_1213_p1;
assign z3_2_fu_1216_p2 = (z1_1_reg_2189 - z3_2_fu_1216_p1);
assign z3_3_1_fu_1491_p1 = z1_3_1_fu_1488_p1;
assign z3_3_1_fu_1491_p2 = (grp_fu_662_p2 - z3_3_1_fu_1491_p1);
assign z3_3_fu_1145_p1 = z1_3_fu_1142_p1;
assign z3_3_fu_1145_p2 = (grp_fu_650_p2 - z3_3_fu_1145_p1);
assign z3_4_1_fu_1617_p1 = $signed(tmp_40_reg_2405);
assign z3_4_fu_1271_p1 = $signed(tmp_84_reg_2207);
assign z3_5_1_fu_1602_p1 = $signed(tmp_58_reg_2415);
assign z3_5_fu_1256_p1 = $signed(tmp_86_reg_2217);
assign z3_6_1_fu_1587_p1 = $signed(tmp_62_reg_2420);
assign z3_6_fu_1241_p1 = $signed(tmp_88_reg_2222);
assign z3_7_1_fu_1572_p1 = $signed(tmp_54_reg_2410);
assign z3_7_fu_1226_p1 = $signed(tmp_85_reg_2212);
always @ (posedge ap_clk)
begin
    Yc_addr_9_reg_1872[2:0] <= 3'b000;
    Yc_addr_reg_1878[2:0] <= 3'b100;
    Yc_addr_1_reg_1884[2:0] <= 3'b110;
    Yc_addr_2_reg_1889[2:0] <= 3'b010;
    Yc_addr_3_reg_1894[2:0] <= 3'b001;
    Yc_addr_4_reg_1900[2:0] <= 3'b111;
    Yc_addr_5_reg_1906[2:0] <= 3'b011;
    Yc_addr_6_reg_1912[2:0] <= 3'b101;
    tmp1_reg_1938[0] <= 1'b0;
    ptData3_0_sum238241_i_cast_reg_1954[31:7] <= 25'b0000000000000000000000000;
    in_addr_1_reg_1959[0] <= 1'b0;
    row_cast_reg_1975[5:4] <= 2'b00;
    tmp_2_reg_1994[2:0] <= 3'b000;
    tmp_2_cast_reg_1999[2:0] <= 3'b000;
    tmp_2_cast_reg_1999[31:6] <= 26'b00000000000000000000000000;
    tmp_49_cast_reg_2012[31:6] <= 26'b00000000000000000000000000;
    Y_addr_9_reg_2022[2:0] <= 3'b000;
    column_cast_reg_2239[5:4] <= 2'b00;
    row_1_cast_reg_2253[31:4] <= 28'b0000000000000000000000000000;
    Idct_addr_4_reg_2485[1:0] <= 2'b00;
end



endmodule //IDCT_thread

