# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2012.4
# Copyright (C) 2012 Xilinx Inc. All rights reserved.
# 
# ==============================================================

source check_sim.tcl
### systemc simulation ###
puts "@I \[SIM-11\] Starting SystemC simulation ..."
cd ../systemc
#remove hdltvin&hdltvout in tv dir
file delete -force [file join "../tv" IDCT.hdltvin.dat]
file delete -force [file join "../tv" IDCT.hdltvout.dat]
        set ::env(AP_WRITE_TV) "on"
file delete -force  "err.log"
if {![file exists cosim.sc.exe]} {
    puts "@E \[SIM-320\] Generating test vectors failed. Please re-run cosim."
}
set ret [catch {eval exec ./cosim.sc.exe | tee temp1.log >&@ stdout} err]
if {[file isfile IDCT.hdltvin.dat]} {
    file copy -force IDCT.hdltvin.dat [file join "../tv" IDCT.hdltvin.dat]
}
if {[file isfile IDCT.hdltvout.dat]} {
    file copy -force IDCT.hdltvout.dat [file join "../tv" IDCT.hdltvout.dat]
}
sc_sim_check $ret $err "temp1.log"

